"""Shared Inspect-sandbox plumbing for the isolation validation suites.

``tests/test_oeis_isolation.py`` and ``tests/test_fc100_isolation.py`` both
validate committed ``Isolated/`` specs by running the Lean declaration-range
extractor and the scorer's ``lake env lean -o`` compile inside a container.
There is no local Lean toolchain, so the container is the ``generate`` stage of
``apn/lean/Dockerfile`` (the ``base`` Lean + Mathlib + FormalConjectures stage
plus the baked ``extract_ranges`` binary), brought up through Inspect's own
sandbox lifecycle (``task_init`` / ``init_sandbox_environments_sample`` /
``cleanup``) from a compose file that carries a ``build:`` section, exactly
like ``tests/test_singlefile_proof.py`` and a real eval -- so docker (re)builds
the image from the current Dockerfile on demand, cache-backed, and a stale
prebuilt image can never silently satisfy the test. No raw ``docker`` CLI, no
host bind mount, no pre-provisioned dev container: host ``.lean`` files are
staged *into* the sandbox as a tar, and the extractor/compiler run via
``sandbox.exec``. (The vendor-time ``scripts/generate_*_isolated.py`` tools
still drive a warm dev container over the docker CLI -- interactive tools, not
gated tests -- and share the pure cut logic and the compile script with these
suites via ``scripts/isolation.py``.)
"""

from __future__ import annotations

import io
import tarfile
import tempfile
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any, cast

from inspect_ai.util._sandbox.context import (
    cleanup_sandbox_environments_sample,
    init_sandbox_environments_sample,
)
from inspect_ai.util._sandbox.docker.docker import DockerSandboxEnvironment

from apn import __version__
from apn.task import (
    IMAGE_REPOSITORY,
    _build_section,
    _docker_tag_component,
    get_identifier_for_image,
)
from scripts.isolation import BAKED_EXE, CONTAINER_PROJECT, COMPILE_SCRIPT, parse_extractor_output


def generate_compose_file() -> str:
    """Path to a one-service compose that builds the Dockerfile's ``generate``
    stage. Reuses ``apn.task``'s build-section + version-tag helpers, so the
    image is current by construction (``build:`` rebuilds from the Dockerfile)
    and never pinned to a stale fixed tag."""
    tag = get_identifier_for_image("generate")
    content = f"""# Generated by tests/lean_sandbox.py -- the Dockerfile `generate` stage
# (base Lean/Mathlib/FormalConjectures + the baked extract_ranges binary).
services:
  default:
    image: {IMAGE_REPOSITORY}:{tag}
{_build_section("generate")}    init: true
    entrypoint: tail -f /dev/null
    mem_limit: 32g
    network_mode: none
"""
    d = Path(tempfile.gettempdir()) / "apn_generate_compose" / _docker_tag_component(__version__)
    d.mkdir(parents=True, exist_ok=True)
    path = d / "compose.yaml"
    if not path.exists() or path.read_text() != content:
        path.write_text(content)
    return str(path)


@asynccontextmanager
async def generate_env(task_name: str) -> AsyncIterator[DockerSandboxEnvironment]:
    """Bring up the ``generate`` compose and yield the live sandbox env.

    Per-session bring-up/tear-down through Inspect's sandbox lifecycle (the same
    path a real eval uses); the docker cache keeps repeat runs cheap. Mirrors
    ``tests/test_singlefile_proof.py::_sandbox_envs``.
    """
    compose = generate_compose_file()
    await DockerSandboxEnvironment.task_init(task_name, compose)
    try:
        envs = await init_sandbox_environments_sample(
            sandboxenv_type=DockerSandboxEnvironment,
            task_name=task_name,
            config=compose,
            files={},
            setup=None,
            metadata={},
        )
        try:
            yield cast(DockerSandboxEnvironment, envs["default"])
        finally:
            await cleanup_sandbox_environments_sample(
                type="docker",
                task_name=task_name,
                config=compose,
                environments=envs,
                interrupted=False,
            )
    finally:
        await DockerSandboxEnvironment.task_cleanup(task_name, compose, cleanup=True)


# Where host .lean files are staged inside the sandbox; members keep their
# arcname (basename by default, or a caller-supplied relative path -- FC100's
# sources need relpaths because its tree has basename collisions, e.g.
# ErdosProblems/23.lean vs OpenQuantumProblems/23.lean). A fresh dir per batch.
_STAGE_DIR = "/tmp/apn_iso"
_STAGE_TAR = "/tmp/apn_iso_batch.tar"


async def stage(
    env: DockerSandboxEnvironment, files: list[Path], arcnames: list[str] | None = None
) -> list[str]:
    """Copy host ``files`` into the sandbox as one tar and return their in-sandbox
    paths. One ``write_file`` + one ``exec`` per batch (vs a write per file)."""
    if arcnames is None:
        arcnames = [p.name for p in files]
    assert len(set(arcnames)) == len(files), "staging arcnames collide"
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w") as tf:
        for p, arc in zip(files, arcnames):
            tf.add(p, arcname=arc)
    await env.write_file(_STAGE_TAR, buf.getvalue())
    res = await env.exec(
        ["bash", "-c", f"rm -rf {_STAGE_DIR} && mkdir -p {_STAGE_DIR} "
         f"&& tar -xf {_STAGE_TAR} -C {_STAGE_DIR}"]
    )
    assert res.success, f"staging files into sandbox failed:\n{res.stderr}"
    return [f"{_STAGE_DIR}/{arc}" for arc in arcnames]


async def extract(
    env: DockerSandboxEnvironment, files: list[Path], arcnames: list[str] | None = None
) -> list[dict[str, Any]]:
    """Run ``extract_ranges`` over ``files`` (under ``lake env``) in the sandbox.

    Each returned record's ``file`` is rewritten to its *arcname* (basename or
    caller-supplied relative path), so callers key records the same way they
    named the staged files.
    """
    cpaths = await stage(env, files, arcnames)
    res = await env.exec(["lake", "env", BAKED_EXE, *cpaths], cwd=CONTAINER_PROJECT)
    if not res.success:
        raise RuntimeError(f"extractor failed (rc={res.returncode}):\n{res.stderr[-3000:]}")
    records: list[dict[str, Any]] = parse_extractor_output(res.stdout)
    prefix = f"{_STAGE_DIR}/"
    for fr in records:
        assert fr["file"].startswith(prefix), fr["file"]
        fr["file"] = fr["file"][len(prefix):]
    return records


async def compile_all(env: DockerSandboxEnvironment, files: list[Path]) -> list[str]:
    """Compile every file with the scorer's ``lake env lean -o`` command in the
    sandbox; return the stems that failed. Uses the shared ``COMPILE_SCRIPT``."""
    cpaths = await stage(env, files)
    res = await env.exec(["bash", "-s", "--", *cpaths], input=COMPILE_SCRIPT)
    if not res.success:
        raise RuntimeError(f"compile driver failed (rc={res.returncode}):\n{res.stderr[-3000:]}")
    return sorted(s for s in res.stdout.split() if s)
