"""Authoritative validation of the committed ``apn/data/oeis/Isolated/`` specs.

``scripts/generate_isolated.py`` only *writes* the isolated files; the checks
that prove they are sound live here. There is no local Lean toolchain, so these
run the extractor and the ``lake env lean -o`` compile (the same elaboration the
scorer performs at eval time) inside a container -- "CI has no Lean" is not a
reason to weaken the gate; we bring Lean up in Docker.

The container is the ``generate`` stage of ``apn/lean/Dockerfile`` (the ``base``
Lean + Mathlib + FormalConjectures stage plus the baked ``extract_ranges``
binary). It is brought up through Inspect's own sandbox lifecycle
(``task_init`` / ``init_sandbox_environments_sample`` / ``cleanup``) from a
compose file that carries a ``build:`` section, exactly like
``tests/test_singlefile_proof.py`` and a real eval -- so docker (re)builds the
image from the current Dockerfile on demand, cache-backed, and a stale prebuilt
image can never silently satisfy the test. No raw ``docker`` CLI, no host bind
mount, no pre-provisioned dev container: the repo's ``.lean`` files are staged
*into* the sandbox as a tar, and the extractor/compiler run via ``sandbox.exec``.
(The vendor-time ``scripts/generate_isolated.py`` still drives a warm dev
container over the docker CLI -- an interactive tool, not a gated test -- and
shares the pure cut logic and the compile script with this module.)

The gates (all over the committed files, recomputing independently what *should*
be true):

* **Structural** -- re-extract each isolated file and confirm the target theorem
  is present exactly once, the surviving theorem/lemma commands are exactly the
  ones the cut predicts (target + its definitional-dependency lemmas, nothing
  else), and the target's elaborated statement is byte-for-byte the source's.
* **Compile** -- every isolated file compiles cleanly with the scorer's exact
  command, in parallel in the container.
* **Oracle** -- for the paper's solved problems, our isolated target's elaborated
  type matches the published challenge file's ``target_theorem_0``.

Docker is part of the test environment, so these always run -- they are not
gated or skipped. The first run builds the image (Lean + Mathlib) from the
Dockerfile; subsequent runs reuse the docker layer cache.
"""

from __future__ import annotations

import io
import tarfile
import tempfile
from contextlib import asynccontextmanager
from dataclasses import dataclass
from pathlib import Path

import pytest
import pytest_asyncio
from inspect_ai.util._sandbox.context import (
    cleanup_sandbox_environments_sample,
    init_sandbox_environments_sample,
)
from inspect_ai.util._sandbox.docker.docker import DockerSandboxEnvironment

from apn import __version__
from apn.task import (
    IMAGE_REPOSITORY,
    _build_section,
    _docker_tag_component,
    get_identifier_for_image,
)
from scripts.oeis_isolation import (
    AUTO_DIR,
    BAKED_EXE,
    CONTAINER_PROJECT,
    COMPILE_SCRIPT,
    ISOLATED_DIR,
    MAPPING_FILE,
    matches_name,
    parse_extractor_output,
    parse_mapping,
    planned_survivors,
    theorem_command_decls,
    theorem_decls,
)

# The paper's published challenge files (the oracle cross-checks our isolated
# target's elaborated type against each one's ``target_theorem_0``). Vendored and
# committed under tests/data (NOT read from the gitignored ``reference_sources/``
# clone, which is absent in CI) -- see tests/data/gold_proofs/README.md.
REF_DIR = Path(__file__).resolve().parent / "data" / "gold_proofs"


# --------------------------------------------------------------------------- #
# Sandbox bring-up: the `generate` stage via Inspect's lifecycle + compose.    #
# --------------------------------------------------------------------------- #
def _generate_compose_file() -> str:
    """Path to a one-service compose that builds the Dockerfile's ``generate``
    stage. Reuses ``apn.task``'s build-section + version-tag helpers, so the
    image is current by construction (``build:`` rebuilds from the Dockerfile)
    and never pinned to a stale fixed tag."""
    tag = get_identifier_for_image("generate")
    content = f"""# Generated by tests/test_oeis_isolation.py -- the Dockerfile `generate` stage
# (base Lean/Mathlib/FormalConjectures + the baked extract_ranges binary).
services:
  default:
    image: {IMAGE_REPOSITORY}:{tag}
{_build_section("generate")}    init: true
    entrypoint: tail -f /dev/null
    mem_limit: 32g
    network_mode: none
"""
    d = Path(tempfile.gettempdir()) / "apn_generate_compose" / _docker_tag_component(__version__)
    d.mkdir(parents=True, exist_ok=True)
    path = d / "compose.yaml"
    if not path.exists() or path.read_text() != content:
        path.write_text(content)
    return str(path)


@asynccontextmanager
async def _generate_env():
    """Bring up the ``generate`` compose and yield the live sandbox env.

    Per-session bring-up/tear-down through Inspect's sandbox lifecycle (the same
    path a real eval uses); the docker cache keeps repeat runs cheap. Mirrors
    ``tests/test_singlefile_proof.py::_scorer_env``.
    """
    compose = _generate_compose_file()
    task_name = "pytest_oeis_isolation"
    await DockerSandboxEnvironment.task_init(task_name, compose)
    try:
        envs = await init_sandbox_environments_sample(
            sandboxenv_type=DockerSandboxEnvironment,
            task_name=task_name,
            config=compose,
            files={},
            setup=None,
            metadata={},
        )
        try:
            yield envs["default"]
        finally:
            await cleanup_sandbox_environments_sample(
                type="docker",
                task_name=task_name,
                config=compose,
                environments=envs,
                interrupted=False,
            )
    finally:
        await DockerSandboxEnvironment.task_cleanup(task_name, compose, cleanup=True)


# Where host .lean files are staged inside the sandbox (flat: members keep their
# basename, which is how records are keyed back). A fresh dir per batch.
_STAGE_DIR = "/tmp/apn_iso"
_STAGE_TAR = "/tmp/apn_iso_batch.tar"


async def _stage(env: DockerSandboxEnvironment, files: list[Path]) -> list[str]:
    """Copy host ``files`` into the sandbox as one tar and return their in-sandbox
    paths. One ``write_file`` + one ``exec`` per batch (vs a write per file)."""
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w") as tf:
        for p in files:
            tf.add(p, arcname=p.name)
    await env.write_file(_STAGE_TAR, buf.getvalue())
    res = await env.exec(
        ["bash", "-c", f"rm -rf {_STAGE_DIR} && mkdir -p {_STAGE_DIR} "
         f"&& tar -xf {_STAGE_TAR} -C {_STAGE_DIR}"]
    )
    assert res.success, f"staging files into sandbox failed:\n{res.stderr}"
    return [f"{_STAGE_DIR}/{p.name}" for p in files]


async def _extract(env: DockerSandboxEnvironment, files: list[Path]) -> list[dict]:
    """Run ``extract_ranges`` over ``files`` (under ``lake env``) in the sandbox."""
    cpaths = await _stage(env, files)
    res = await env.exec(["lake", "env", BAKED_EXE, *cpaths], cwd=CONTAINER_PROJECT)
    if not res.success:
        raise RuntimeError(f"extractor failed (rc={res.returncode}):\n{res.stderr[-3000:]}")
    return parse_extractor_output(res.stdout)


async def _compile_all(env: DockerSandboxEnvironment, files: list[Path]) -> list[str]:
    """Compile every file with the scorer's ``lake env lean -o`` command in the
    sandbox; return the stems that failed. Uses the shared ``COMPILE_SCRIPT``."""
    cpaths = await _stage(env, files)
    res = await env.exec(["bash", "-s", "--", *cpaths], input=COMPILE_SCRIPT)
    if not res.success:
        raise RuntimeError(f"compile driver failed (rc={res.returncode}):\n{res.stderr[-3000:]}")
    return sorted(s for s in res.stdout.split() if s)


# --------------------------------------------------------------------------- #
# Fixtures: extract + compile once, in one sandbox, share the results.         #
# --------------------------------------------------------------------------- #
@dataclass
class IsoData:
    """Everything the gates need, gathered from a single sandbox bring-up."""

    auto_ranges: dict[str, dict]  # extractor records for distinct Auto/ sources, by filename
    iso_ranges: dict[str, dict]  # extractor records for every Isolated/ file, by stem (= name)
    ref_ranges: list[dict]  # extractor records for the published challenge files
    compile_failures: list[str]  # stems of Isolated/ files that failed to compile


@pytest.fixture(scope="session")
def mapping() -> list[tuple[str, list[str]]]:
    entries = parse_mapping(MAPPING_FILE.read_text())
    assert len(entries) == 492
    return entries


@pytest_asyncio.fixture(loop_scope="module", scope="module")
async def iso_data(mapping) -> IsoData:
    """Bring the sandbox up once and run every Lean step inside it: extract the
    Auto sources, the Isolated files, and the reference challenge files, then
    compile every Isolated file.

    An async, module-scoped fixture (with the gate tests on the same module-scoped
    event loop) -- the only safe way to drive Inspect's sandbox lifecycle from
    pytest. Driving it from a plain fixture via ``asyncio.run`` would spin up a
    second event loop that Inspect's loop-bound globals deadlock against; sharing
    pytest-asyncio's own loop avoids that. The gates below just assert against the
    returned data, so they need no further sandbox access."""
    async with _generate_env() as env:
        source_files = sorted({files[0] for _, files in mapping})
        auto = await _extract(env, [AUTO_DIR / f for f in source_files])
        iso_files = sorted(ISOLATED_DIR.glob("*.lean"))
        iso = await _extract(env, iso_files)
        ref_files = sorted(REF_DIR.glob("*.lean"))
        ref = await _extract(env, ref_files) if ref_files else []
        failures = await _compile_all(env, iso_files)
    return IsoData(
        auto_ranges={fr["file"].rsplit("/", 1)[-1]: fr for fr in auto},
        iso_ranges={fr["file"].rsplit("/", 1)[-1][: -len(".lean")]: fr for fr in iso},
        ref_ranges=ref,
        compile_failures=failures,
    )


# --------------------------------------------------------------------------- #
# Gates. Async + module-scoped loop so they share the one sandbox bring-up      #
# above; the bodies are pure assertions over the precomputed ``iso_data``.      #
# --------------------------------------------------------------------------- #
@pytest.mark.asyncio(loop_scope="module")
async def test_isolated_files_are_structurally_correct(mapping, iso_data) -> None:
    """Each isolated file carries exactly the target + its dependency lemmas (the
    cut's prediction), with the target's statement preserved verbatim."""
    failures: list[str] = []
    for name, files in mapping:
        src_type, planned = planned_survivors(iso_data.auto_ranges[files[0]], name)
        fr = iso_data.iso_ranges.get(name)
        if fr is None:
            failures.append(f"{name}: no isolated file extracted")
            continue
        thms = theorem_command_decls(fr)
        target_hits = [d for d in thms if matches_name(d["name"], name)]
        if len(target_hits) != 1:
            failures.append(f"{name}: target appears {len(target_hits)}x among {[d['name'] for d in thms]}")
            continue
        remaining = sorted(d["name"] for d in thms)
        if remaining != planned:
            failures.append(f"{name}: surviving theorems {remaining} != planned {planned}")
            continue
        if target_hits[0]["type"] != src_type:
            failures.append(f"{name}: target statement changed during isolation")
    assert not failures, "structural validation failed:\n  " + "\n  ".join(failures)


@pytest.mark.asyncio(loop_scope="module")
async def test_isolated_files_compile(iso_data) -> None:
    """The authoritative gate: every isolated file compiles with the scorer's
    exact ``lake env lean -o`` command."""
    assert not iso_data.compile_failures, (
        f"{len(iso_data.compile_failures)} isolated file(s) failed to compile: "
        f"{iso_data.compile_failures}"
    )


@pytest.mark.asyncio(loop_scope="module")
async def test_oracle_matches_published_challenge_files(iso_data) -> None:
    """For each solved problem the paper published, our isolated target's
    elaborated type matches its ``target_theorem_0`` (the paper renames the
    conjecture). Confirms isolation reproduces the published challenge statement."""
    if not iso_data.ref_ranges:
        pytest.skip("no reference challenge files vendored")

    def target_type(name: str, fr: dict) -> str:
        (target,) = [d for d in theorem_command_decls(fr) if matches_name(d["name"], name)]
        return target["type"]

    iso_types = {name: target_type(name, fr) for name, fr in iso_data.iso_ranges.items()}
    match = mismatch = 0
    mismatches: list[str] = []
    for fr in iso_data.ref_ranges:
        name = fr["file"].rsplit("/", 1)[-1][: -len(".lean")]
        if name not in iso_types:
            continue
        tgt = [d for d in theorem_decls(fr) if matches_name(d["name"], "target_theorem_0")]
        if len(tgt) != 1:
            continue
        if tgt[0]["type"] == iso_types[name]:
            match += 1
        else:
            mismatch += 1
            mismatches.append(name)
    assert mismatch == 0, f"oracle mismatch for: {mismatches}"
    assert match == len(iso_data.ref_ranges), (
        f"only {match}/{len(iso_data.ref_ranges)} reference files matched"
    )
