"""Inspect task for AlphaProof Nexus.

Run the agent over the OEIS conjectures::

    inspect eval apn/task.py@apn_oeis --model openai/gpt-5.5 --token-limit 1000000

The sandbox images are built automatically by docker compose at eval startup
from the multi-stage apn/lean/Dockerfile (and rebuilt when it changes); the
first local run pays the full Lean + Mathlib build. With ``literature=True`` the
agent runs against the agent-corpus image, which additionally bakes in the
offline arXiv-math corpus at /corpus (apn/lean/fetch.py + build_corpus.py) -- its first
build also pays the corpus download. In production, LEAN_OPEN_PROBLEMS_IMAGE_NAME
points at the registry that CI pushed the images to.

Run several independent attempts per problem with ``--epochs N`` (each epoch is a
fresh sample run with its own sandbox); pair it with an epoch reducer such as
``--epochs 4,pass_at_1`` if you want any-success scoring.
"""

from __future__ import annotations

import re
import tempfile
from pathlib import Path

from inspect_ai import Task, task

from apn import __version__
from apn.agent import AgentType, lean_prover
from apn.checker import SandboxSafeVerify
from apn.dataset import oeis_dataset
from apn.scorer import proof_scorer

COMPOSE_FILES_DIR = Path(tempfile.gettempdir()) / "leanopenproblems_compose"
IMAGE_REPOSITORY = "${LEAN_OPEN_PROBLEMS_IMAGE_NAME:-leanopenproblems}"


def _docker_tag_component(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]", "_", value)


def get_identifier_for_image(image_kind: str) -> str:
    image_version = _docker_tag_component(__version__)
    return f"LeanOpenProblems_{image_kind}_{image_version}"


def _build_section(target: str) -> str:
    """A compose ``build:`` section (PortBench's pattern: build + image).

    Locally the image doesn't exist, so docker compose builds it from the
    multi-stage apn/lean/Dockerfile at eval startup -- no manual image
    management. The two services share the heavyweight ``base`` stage (Lean +
    Mathlib + FormalConjectures oleans) through the build cache.
    """
    return f"""\
    build:
      context: {Path(__file__).parent / "lean"}
      target: {target}
"""


def get_compose_file_content(literature: bool = False) -> str:
    # Literature runs use the agent-corpus image (the offline arXiv corpus baked
    # in at /corpus); closed-book runs use the plain agent image, which has no
    # /corpus at all -- so closed-book is hermetic, not merely unprompted.
    agent_kind = "agent_corpus" if literature else "agent"
    agent_tag = get_identifier_for_image(agent_kind)
    scorer_tag = get_identifier_for_image("scorer")
    return f"""# Generated by apn.task.
# Two sandboxes per sample:
#   - default: the agent's workspace ({IMAGE_REPOSITORY}:{agent_tag}) --
#              PyPantograph + Lean/Mathlib/FormalConjectures oleans baked in,
#              so the agent can spin up a ``pantograph.Server`` from python3.
#              No SafeVerify here.
#   - scorer:  a separate, trusted container
#              ({IMAGE_REPOSITORY}:{scorer_tag})
#              the agent never writes to, where SafeVerify validates the final
#              proof.
# Run several independent attempts per problem with `inspect eval ... --epochs N`.
#
# LEAN_OPEN_PROBLEMS_IMAGE_NAME is the image repository name. The tag after the
# colon identifies which sandbox image to use, following PortBench's generated
# compose pattern: each service carries both build: and image:, so local runs
# build the images on demand from the local Dockerfiles.
services:
  default:
    image: {IMAGE_REPOSITORY}:{agent_tag}
{_build_section(agent_kind)}    init: true
    entrypoint: tail -f /dev/null
    # A full PyPantograph session (Server + check_compile + load_sorry +
    # goal_tactic on a benchmark file) peaks at ~6 GiB RSS, almost all of it
    # mmapped Mathlib oleans -- shared between processes and reclaimable under
    # pressure (only ~0.4 GiB is anonymous). 10g is comfortable headroom for
    # the normal workflow; if agent code exceeds it anyway, the OOM kill is
    # reported back through the bash tool and the agent can adapt.
    mem_limit: 10g
    network_mode: none
  scorer:
    image: {IMAGE_REPOSITORY}:{scorer_tag}
{_build_section("scorer")}    init: true
    entrypoint: tail -f /dev/null
    # safe_verify has a large fixed footprint: ~27 GiB peak RSS (~21 GiB
    # anonymous), flat to within 0.1 GiB across benchmark samples. Phase-by-
    # phase profiling attributes essentially all of it to four importModules
    # calls (two in the import-superset check, one per replayed file), each
    # materializing the full Mathlib environment on the heap and never freeing
    # it; the kernel replay of the submission's own declarations is negligible
    # by comparison.
    #
    # On top of that baseline, proof *content* adds kernel-checking work, and
    # this part is effectively unbounded for legitimate proofs: safe_verify's
    # rebuildExpr deep-copies proof terms *without memoization*, expanding
    # pointer-shared DAGs (which tactics like `ring` produce routinely) into
    # trees. Measured example: `(a+b+c)^16 = (c+b+a)^16 := by ring` compiles
    # in 3.5s at 6.4 GiB but blew past a 34 GiB limit in safe_verify before
    # being OOM-killed. So the agent-side compile succeeding does NOT bound
    # the scorer's cost, and no mem_limit can make scorer OOMs impossible.
    # Real submissions have reached ~43 GiB in production monitoring.
    #
    # The real fixes live in the vendored safeverify (memoize rebuildExpr;
    # skip the redundant importModules in the superset check) -- deliberately
    # not attempted for now: changing verifier code is risky. 50g covers the
    # fixed baseline plus the worst production observation to date. An OOM
    # kill here is an infrastructure error (the checker raises rather than
    # mis-scoring the proof), and it is deterministic per submission, so it
    # will recur on retry.
    mem_limit: 50g
    network_mode: none
"""


def get_compose_file(literature: bool = False) -> Path:
    # Distinct filenames so the closed-book and literature composes (different
    # default images) coexist without clobbering each other.
    name = "compose-corpus.yaml" if literature else "compose.yaml"
    compose_path = COMPOSE_FILES_DIR / _docker_tag_component(__version__) / name
    compose_path.parent.mkdir(parents=True, exist_ok=True)
    content = get_compose_file_content(literature)
    if not compose_path.exists() or compose_path.read_text() != content:
        compose_path.write_text(content)
    return compose_path


@task
def apn_oeis(
    names: str | list[str] | None = None,
    gated: bool = False,
    literature: bool = False,
    agent_type: AgentType = "react",
) -> Task:
    """Prove the autoformalized OEIS conjectures from the paper (44/492).

    Replicates the paper's OEIS evaluation: each sample is an autoformalized OEIS
    conjecture from Formal Conjectures (``OEIS/Auto``). The agent must discharge
    the embedded *test lemmas* (small-term checks guarding against
    misformalization) and then *settle* the conjecture -- either prove it or
    disprove it by supplying a ``foo.disproof`` of its negation. SafeVerify then
    re-validates the whole file (every definition and test lemma reproduced
    verbatim and proved sorry-free with only permitted axioms; the conjecture
    accepted via a proof or a kernel-checked negation) -- see
    :class:`~apn.checker.SandboxSafeVerify`.

    Runs against the Formal Conjectures Lean v4.27 sandbox (built automatically
    by docker compose from ``apn/lean/Dockerfile``).

    Args:
        names: Optional comma-separated list of conjecture theorem names to keep
            (a smoke subset); defaults to all 492.
        gated: If true, submissions are gated by SafeVerify -- a submission that
            fails verification is rejected and the agent must keep working (until
            a limit), and it is told only that verification failed (not why).
        literature: If true, run against the agent-corpus image -- the offline
            arXiv-math corpus baked in at ``/corpus`` (a 2022 snapshot, so it
            predates the benchmark paper and can't leak a later solution), which
            the agent greps from its ``bash`` shell. Off by default -- this is a
            distinct, literature-augmented run condition that should be reported
            separately from the closed-book numbers.
        agent_type: Which agent loop to run -- ``"deep"`` (default) for Inspect's
            ``deepagent`` or ``"react"`` for its plain react agent. Both run with
            the same tools, gating, and prompt.
    """
    if names is None:
        name_list = None
    else:
        raw = names.split(",") if isinstance(names, str) else names
        name_list = [n.strip() for n in raw if n.strip()]
    # When gated, the agent re-runs the (task) scorer on every submission via
    # Inspect's `attempts`, bounded only by the token limit; otherwise the first
    # submission ends the loop and is validated once by the final scorer.
    return Task(
        dataset=oeis_dataset(names=name_list),
        solver=lean_prover(
            max_attempts=99_999_999 if gated else 1,
            literature=literature,
            agent_type=agent_type,
        ),
        scorer=proof_scorer(SandboxSafeVerify(sandbox_name="scorer")),
        sandbox=("docker", str(get_compose_file(literature))),
    )
