"""Inspect task for AlphaProof Nexus.

Build the Lean images, then run the agent over the OEIS conjectures::

    apn/lean/build.sh   # builds apn-lean-base, apn-agent, apn-scorer
    inspect eval apn/task.py@apn_oeis --model openai/gpt-5.5 --token-limit 1000000

Run several independent attempts per problem with ``--epochs N`` (each epoch is a
fresh sample run with its own sandbox); pair it with an epoch reducer such as
``--epochs 4,pass_at_1`` if you want any-success scoring.
"""

from __future__ import annotations

import json
import re
import subprocess
import tempfile
from importlib import metadata
from pathlib import Path

from inspect_ai import Task, task

from apn import __version__
from apn.agent import lean_prover
from apn.checker import SandboxSafeVerify
from apn.dataset import oeis_dataset
from apn.scorer import proof_scorer
from apn.verifier.pantograph import PantographVerifier

PROJECT_ROOT = Path(__file__).resolve().parent.parent
COMPOSE_FILES_DIR = Path(tempfile.gettempdir()) / "leanopenproblems_compose"
IMAGE_REPOSITORY = "${LEAN_OPEN_PROBLEMS_IMAGE_NAME:-leanopenproblems}"


def _docker_tag_component(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]", "_", value)


def _commit_from_direct_url() -> str | None:
    distribution_names = [*metadata.packages_distributions().get("apn", []), "apn"]
    for distribution_name in dict.fromkeys(distribution_names):
        try:
            direct_url = metadata.distribution(distribution_name).read_text(
                "direct_url.json"
            )
        except metadata.PackageNotFoundError:
            continue
        if direct_url is not None:
            break
    else:
        return None
    if direct_url is None:
        return None
    try:
        payload: object = json.loads(direct_url)
    except json.JSONDecodeError:
        return None
    if not isinstance(payload, dict):
        return None
    vcs_info = payload.get("vcs_info")
    if not isinstance(vcs_info, dict):
        return None
    commit_id = vcs_info.get("commit_id")
    if isinstance(commit_id, str) and commit_id:
        return commit_id
    return None


def _commit_from_git() -> str | None:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=PROJECT_ROOT,
            check=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    commit = result.stdout.strip()
    return commit or None


def get_source_git_hash() -> str:
    return _commit_from_direct_url() or _commit_from_git() or "local"


def get_identifier_for_image(image_kind: str, source_git_hash: str | None = None) -> str:
    git_hash = _docker_tag_component(source_git_hash or get_source_git_hash())
    image_version = _docker_tag_component(__version__)
    return f"LeanOpenProblems_{image_kind}_{image_version}_{git_hash}"


def get_compose_file_content(source_git_hash: str | None = None) -> str:
    agent_tag = get_identifier_for_image("agent", source_git_hash)
    scorer_tag = get_identifier_for_image("scorer", source_git_hash)
    return f"""# Generated by apn.task.
# Two sandboxes per sample:
#   - default: the agent's workspace
#              ({IMAGE_REPOSITORY}:{agent_tag})
#              -- warm PyPantograph with FormalConjectures.Util.ProblemImports
#              preloaded; no SafeVerify.
#   - scorer:  a separate, trusted container
#              ({IMAGE_REPOSITORY}:{scorer_tag})
#              the agent never writes to, where SafeVerify validates the final
#              proof.
# Run several independent attempts per problem with `inspect eval ... --epochs N`.
#
# LEAN_OPEN_PROBLEMS_IMAGE_NAME is the image repository name. The tag after the
# colon identifies which sandbox image to use, following PortBench's generated
# compose pattern. Tags include the package git hash because ECR tags are
# immutable.
services:
  default:
    image: {IMAGE_REPOSITORY}:{agent_tag}
    init: true
    entrypoint: tail -f /dev/null
    mem_limit: 15g
    network_mode: none
  scorer:
    image: {IMAGE_REPOSITORY}:{scorer_tag}
    init: true
    entrypoint: tail -f /dev/null
    mem_limit: 15g
    network_mode: none
"""


def get_compose_file() -> Path:
    source_git_hash = get_source_git_hash()
    compose_path = COMPOSE_FILES_DIR / _docker_tag_component(source_git_hash) / "compose.yaml"
    compose_path.parent.mkdir(parents=True, exist_ok=True)
    content = get_compose_file_content(source_git_hash)
    if not compose_path.exists() or compose_path.read_text() != content:
        compose_path.write_text(content)
    return compose_path


@task
def apn_oeis(
    names: str | list[str] | None = None,
    gated: bool = False,
    literature: bool = False,
) -> Task:
    """Prove the autoformalized OEIS conjectures from the paper (44/492).

    Replicates the paper's OEIS evaluation: each sample is an autoformalized OEIS
    conjecture from Formal Conjectures (``OEIS/Auto``). The agent must discharge
    the embedded *test lemmas* (small-term checks guarding against
    misformalization) as well as the conjecture; SafeVerify then re-validates the
    whole file (every definition, test lemma, and the conjecture must be
    reproduced verbatim and proved sorry-free with only permitted axioms).

    Runs against the Formal Conjectures Lean v4.27 sandbox (build it first with
    ``apn/lean/build.sh``).

    Args:
        names: Optional comma-separated list of conjecture theorem names to keep
            (a smoke subset); defaults to all 492.
        gated: If true, submissions are gated by SafeVerify -- a submission that
            fails verification is rejected and the agent must keep working (until
            a limit), and it is told only that verification failed (not why).
        literature: If true, give the agent ``arxiv_search`` / ``arxiv_source``
            (gated to papers predating the benchmark paper). Off by default --
            this is a distinct, literature-augmented run condition that should be
            reported separately from the closed-book numbers.
    """
    if names is None:
        name_list = None
    else:
        raw = names.split(",") if isinstance(names, str) else names
        name_list = [n.strip() for n in raw if n.strip()]
    # When gated, the agent re-runs the (task) scorer on every submission via
    # Inspect's `attempts`, bounded only by the token limit; otherwise the first
    # submission ends the loop and is validated once by the final scorer.
    return Task(
        dataset=oeis_dataset(names=name_list),
        solver=lean_prover(
            PantographVerifier(),
            max_attempts=99_999_999 if gated else 1,
            literature=literature,
        ),
        scorer=proof_scorer(SandboxSafeVerify(sandbox_name="scorer")),
        sandbox=("docker", str(get_compose_file())),
    )
