"""Render rows of conjectures.jsonl (see collect.py) as a LaTeX longtable.

Usage:
    python scripts/summarize/latex_table.py out/conjectures.jsonl -n 20 -o table.tex

Rows are sorted by descending proof cost. Text is escaped outside math spans
(both \\(...\\) and $...$ delimiters); disproofs are marked with a dagger.
"""

import argparse
import json
import re
import sys
from pathlib import Path

REPLACEMENTS = {
    "\u2019": "'",
    "\u2018": "`",
    "\u201c": "``",
    "\u201d": "''",
    "\u2014": "---",
    "\u2013": "--",
}
SPECIALS = {"%": r"\%", "&": r"\&", "#": r"\#", "_": r"\_"}
MATH_SPAN = re.compile(r"(\\\(.*?\\\)|\$[^$]+\$)")


def escape(text: str) -> str:
    for src, dst in REPLACEMENTS.items():
        text = text.replace(src, dst)
    parts = MATH_SPAN.split(text)
    for i, part in enumerate(parts):
        if i % 2 == 0:
            if "`" in part:
                print(f"warning: backtick outside math: {part!r}", file=sys.stderr)
            for src, dst in SPECIALS.items():
                part = part.replace(src, dst)
            parts[i] = part
    return "".join(parts)


# The Sequence column is narrow; long unbreakable formulas (factorial ratios,
# powered binomials) overflow it unless we allow breaks between factors.
BREAKPOINTS = [
    (")!(", r")!\allowbreak("),
    ("!/(", r"!/\allowbreak("),
    (")/(", r")/\allowbreak("),
    (re.compile(r"\^(\d)\\left\("), r"^\1\\allowbreak\\left("),
]


def breakable(text: str) -> str:
    parts = MATH_SPAN.split(text)
    for i, part in enumerate(parts):
        if i % 2:
            for src, dst in BREAKPOINTS:
                if isinstance(src, str):
                    part = part.replace(src, dst)
                else:
                    part = src.sub(dst, part)
            parts[i] = part
    return "".join(parts)


HEADER = r"""% Generated by scripts/summarize/latex_table.py -- do not edit by hand.
{\footnotesize
\renewcommand{\arraystretch}{1.15}
\begin{longtable}{p{0.42\textwidth} p{0.44\textwidth} r}
\caption{<CAPTION>}
\label{tab:fable-top-solves}\\
\hline
\textbf{Sequence and conjecture} & \textbf{Proof summary} & \textbf{Cost} \\ \hline
\endfirsthead
\multicolumn{3}{l}{\footnotesize\emph{Table \ref{tab:fable-top-solves} (continued)}}\\
\hline
\textbf{Sequence and conjecture} & \textbf{Proof summary} & \textbf{Cost} \\ \hline
\endhead
\hline
\endfoot
\endlastfoot
"""

FOOTER = """\\hline
\\end{longtable}
}
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("conjectures", type=Path)
    parser.add_argument("-n", "--top", type=int, default=None,
                        help="keep only the N costliest rows")
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument("--caption", default=None)
    args = parser.parse_args()

    rows = [json.loads(line) for line in args.conjectures.read_text().splitlines() if line.strip()]
    rows.sort(key=lambda r: -r["cost_usd"])
    if args.top:
        rows = rows[: args.top]

    caption = args.caption or (
        f"The {len(rows)} costliest conjectures settled by Claude Fable 5 on "
        r"\benchlite{}, with LM-written summaries."
    )

    lines = [HEADER.replace("<CAPTION>", caption)]
    for r in rows:
        attribution = [x for x in (r.get("proposer"), (r.get("proposed_date") or "")[:4]) if x]
        label = (
            rf"\emph{{Conjecture}} ({escape(', '.join(attribution))})."
            if attribution
            else r"\emph{Conjecture.}"
        )
        statement = (
            rf"\href{{https://oeis.org/{r['oeis_id']}}}{{{r['oeis_id']}}}: "
            + breakable(escape(r["sequence_description"]))
            + rf"\par\smallskip {label} "
            + escape(r["conjecture"])
        )
        verdict = rf"\emph{{{r['verdict'].capitalize()}.}} "
        lines.append(
            f"{statement} & {verdict}{escape(r['proof_summary'])} "
            f"& \\${round(r['cost_usd'])} \\\\ \\hline\n"
        )
    lines.append(FOOTER)
    args.output.write_text("".join(lines))
    print(f"wrote {len(rows)} rows to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
