"""Render rows of conjectures.jsonl (see collect.py) as a LaTeX longtable.

Usage:
    python scripts/summarize/latex_table.py out/conjectures.jsonl -n 20 -o table.tex

Rows are sorted by descending proof cost. Outside math spans, text is escaped
and accents are reduced to ASCII accent commands; the verdict prefixes the
proof summary.
"""

import argparse
import json
import re
import sys
import unicodedata
from pathlib import Path

REPLACEMENTS = {
    "\u2019": "'",
    "\u2018": "`",
    "\u201c": "``",
    "\u201d": "''",
    "\u2014": "---",
    "\u2013": "--",
    # Summaries occasionally drop a bare math glyph into prose, which is a hard
    # LaTeX error outside math mode.
    "\u2261": r"\(\equiv\)",
    "\u2264": r"\(\le\)",
    "\u2265": r"\(\ge\)",
    "\u2260": r"\(\ne\)",
    "\u2208": r"\(\in\)",
    "\u2223": r"\(\mid\)",
    "\u2192": r"\(\to\)",
    "\u00d7": r"\(\times\)",
    "\u22c5": r"\(\cdot\)",
    "\u2212": "$-$",
}
CONTROL = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f]")
# Raw UTF-8 accents render inconsistently across TeX engines and editors, so
# proposer names and cited authors are emitted as ASCII accent commands.
COMBINING = {
    "̀": "`", "́": "'", "̂": "^", "̃": "~", "̄": "=",
    "̆": "u", "̇": ".", "̈": '"', "̊": "r", "̋": "H",
    "̌": "v", "̧": "c", "̨": "k", "̱": "b",
}
LIGATURES = {"ø": r"\o{}", "Ø": r"\O{}", "ł": r"\l{}", "Ł": r"\L{}",
             "ß": r"\ss{}", "æ": r"\ae{}", "Æ": r"\AE{}", "œ": r"\oe{}", "Œ": r"\OE{}"}


def deaccent(text: str) -> str:
    out = []
    for ch in text:
        if ord(ch) < 127:
            out.append(ch)
            continue
        if ch in LIGATURES:
            out.append(LIGATURES[ch])
            continue
        decomposed = unicodedata.normalize("NFD", ch)
        if len(decomposed) == 2 and decomposed[1] in COMBINING:
            out.append(f"\\{COMBINING[decomposed[1]]}{{{decomposed[0]}}}")
        else:
            print(f"warning: unmapped non-ascii {ch!r} (U+{ord(ch):04X})", file=sys.stderr)
            out.append(ch)
    return "".join(out)


SPECIALS = {
    "%": r"\%",
    "&": r"\&",
    "#": r"\#",
    "_": r"\_",
    "^": r"\textasciicircum{}",
    "~": r"\textasciitilde{}",
    "<": r"\textless{}",
    ">": r"\textgreater{}",
}
MATH_SPAN = re.compile(r"(\\\(.*?\\\)|\\\[.*?\\\]|\$[^$]+\$)")
# Display math cannot fit these narrow columns, so it is folded to inline.
DISPLAY_MATH = re.compile(r"\\\[(.*?)\\\]")
# Summaries name Lean tactics/lemmas in markdown code spans; a bare backtick
# would set as a quote mark, so these become \texttt before quotes are mapped.
CODE_SPAN = re.compile(r"`([^`]+)`")


def escape(text: str) -> str:
    text = CONTROL.sub("", text)
    text = DISPLAY_MATH.sub(r"\\(\1\\)", text)
    text = CODE_SPAN.sub(r"\\texttt{\1}", text)
    if "`" in text:
        print(f"warning: unpaired backtick: {text!r}", file=sys.stderr)
    for src, dst in REPLACEMENTS.items():
        text = text.replace(src, dst)
    parts = MATH_SPAN.split(text)
    for i, part in enumerate(parts):
        if i % 2 == 0:
            for src, dst in SPECIALS.items():
                part = part.replace(src, dst)
            parts[i] = deaccent(part)
    return "".join(parts)


# The Sequence column is narrow; long unbreakable formulas (factorial ratios,
# powered binomials) overflow it unless we allow breaks between factors.
BREAKPOINTS = [
    (")!(", r")!\allowbreak("),
    ("!/(", r"!/\allowbreak("),
    (")/(", r")/\allowbreak("),
    (re.compile(r"\^(\d)\\left\("), r"^\1\\allowbreak\\left("),
    # Enumerated values (first-occurrence lists, fixed-point sets) otherwise set
    # as one unbreakable run.
    (",", r",\allowbreak "),
    # A display-size fraction or sum overflows a column this narrow.
    (r"\displaystyle", ""),
]


def breakable(text: str) -> str:
    parts = MATH_SPAN.split(text)
    for i, part in enumerate(parts):
        if i % 2:
            for src, dst in BREAKPOINTS:
                if isinstance(src, str):
                    part = part.replace(src, dst)
                else:
                    part = src.sub(dst, part)
            parts[i] = part
    return "".join(parts)


HEADER = r"""% Generated by scripts/summarize/latex_table.py -- do not edit by hand.
{\footnotesize
\renewcommand{\arraystretch}{1.15}
\begin{longtable}{p{0.42\textwidth} p{0.44\textwidth} r}
\caption{<CAPTION>}
\label{<LABEL>}\\
\hline
\textbf{Sequence and conjecture (LM-written)} & \textbf{Proof summary (LM-written)} & \textbf{Cost} \\ \hline
\endfirsthead
\multicolumn{3}{l}{\footnotesize\emph{Table \ref{<LABEL>} (continued)}}\\
\hline
\textbf{Sequence and conjecture (LM-written)} & \textbf{Proof summary (LM-written)} & \textbf{Cost} \\ \hline
\endhead
\hline
\endfoot
\endlastfoot
"""

FOOTER = """\\hline
\\end{longtable}
}
"""


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("conjectures", type=Path)
    parser.add_argument("-n", "--top", type=int, default=None,
                        help="keep only the N costliest rows")
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument("--caption", default=None)
    parser.add_argument("--label", default="tab:fable-top-solves")
    args = parser.parse_args()

    rows = [json.loads(line) for line in args.conjectures.read_text().splitlines() if line.strip()]
    rows.sort(key=lambda r: -r["cost_usd"])
    if args.top:
        rows = rows[: args.top]

    caption = args.caption or (
        f"The {len(rows)} costliest conjectures settled by Claude Fable 5 on "
        r"\benchlite{}, with LM-written summaries."
    )

    lines = [HEADER.replace("<CAPTION>", caption).replace("<LABEL>", args.label)]
    for r in rows:
        attribution = [x for x in (r.get("proposer"), (r.get("proposed_date") or "")[:4]) if x]
        label = (
            rf"\emph{{Conjecture}} ({escape(', '.join(attribution))})."
            if attribution
            else r"\emph{Conjecture.}"
        )
        statement = (
            rf"\href{{https://oeis.org/{r['oeis_id']}}}{{{r['oeis_id']}}}: "
            + breakable(escape(r["sequence_description"]))
            + rf"\par\smallskip {label} "
            + breakable(escape(r["conjecture"]))
        )
        verdict = rf"\emph{{{r['verdict'].capitalize()}.}} "
        lines.append(
            f"{statement} & {verdict}{breakable(escape(r['proof_summary']))} "
            f"& \\${round(r['cost_usd'])} \\\\ \\hline\n"
        )
    lines.append(FOOTER)
    args.output.write_text("".join(lines))
    print(f"wrote {len(rows)} rows to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
