#!/usr/bin/env python3
"""Regenerate ``lite.json`` -- a seeded random subset of the 492 OEIS conjectures.

The committed ``lite.json`` is the output of this script; rerunning it reproduces
that file byte-for-byte. Run from the repo root::

    uv run python apn/data/oeis/subsets/_gen_lite.py

Why a lite subset: each OEIS sample is a long agent run, so the full 492 is
expensive to sweep. A random subset estimates the full-set pass rate at a
fraction of the cost. At a true rate of ~20% (mid of the observed 10-30%), n=100
gives a 95% CI of about +/-7% after the finite-population correction -- enough to
rank models in that band. Below ~50 the estimate gets too noisy to compare
models; to detect small gaps between similar models, run the full 492.

Reproducibility: the universe is the sorted set of manifest ids, so the draw
does not depend on ``samples.jsonl`` line order; ``random.Random`` is seeded
with a fixed constant. Bump ``SEED`` (not the data) if you ever need a fresh
independent draw, and say so in the description.
"""

from __future__ import annotations

import random
from pathlib import Path

from apn.dataset import OEIS_DIR, load_manifest, write_subset

SEED = 42
N = 100

DESCRIPTION = (
    f"A randomly drawn {N}-conjecture subset of the 492 OEIS Open Problems, for "
    "cheaper runs that still estimate the full-set pass rate. At a true pass rate "
    f"of ~20% (mid of the observed 10-30%), n={N} gives a 95% CI of about +/-7% "
    "after the finite-population correction -- enough to rank models in that band "
    "at ~1/5 the cost of the full run; for detecting small gaps, run the full 492. "
    "Reproducible draw (regenerated byte-for-byte by subsets/_gen_lite.py): "
    f"sorted(random.Random({SEED}).sample(sorted(manifest ids), {N})) -- sorting "
    "the universe first makes the draw independent of manifest line order."
)


def main() -> None:
    universe = sorted(r.id for r in load_manifest(OEIS_DIR))
    assert len(universe) == 492, f"expected 492 conjectures, found {len(universe)}"

    chosen = sorted(random.Random(SEED).sample(universe, N))
    out = write_subset(Path(__file__).resolve().parent / "lite.json", DESCRIPTION, chosen)
    print(f"wrote {out} with {len(chosen)} ids (seed={SEED})")


if __name__ == "__main__":
    main()
