/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Andrews–Curtis conjecture

The Andrews–Curtis conjecture states that every balanced presentation (a presentation with the
same number of generators and relators) of the trivial group can be transformed into a trivial
presentation by a sequence of Nielsen transformations on the relators together with conjugations
of relators. It was proposed by J. J. Andrews and M. L. Curtis in 1965. It is widely believed
to be false, although no counterexample is known.

A balanced presentation on $n$ generators is modelled as an $n$-tuple $(r_1, \dots, r_n)$ of
elements of the free group on $x_1, \dots, x_n$; the presented group is
`PresentedGroup (Set.range r)`. The trivial presentation is the tuple $(x_1, \dots, x_n)$.

*References:*
- [Wikipedia](https://en.wikipedia.org/wiki/Andrews%E2%80%93Curtis_conjecture)
- [Wikipedia, List of unsolved problems in mathematics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics)
- J. J. Andrews, M. L. Curtis, *Free groups and handlebodies*,
  Proc. Amer. Math. Soc. 16 (1965), 192–195. [doi:10.2307/2033843](https://doi.org/10.2307/2033843)
-/

namespace AndrewsCurtisConjecture

/--
An elementary Andrews–Curtis move on an $n$-tuple $(r_1, \dots, r_n)$ of relators in the free
group on $n$ generators. It replaces a single relator $r_i$ by
- its inverse $r_i^{-1}$,
- the product $r_i r_j$ for some $j \ne i$, or
- a conjugate $w r_i w^{-1}$ for some word $w$,

and leaves the other relators unchanged. These are the Nielsen transformations on the relators
(permutations of the relators are generated by the first two kinds of move) together with
conjugations of relators. The generators are fixed: no stabilization moves are allowed.
-/
inductive Move {n : ℕ} : (Fin n → FreeGroup (Fin n)) → (Fin n → FreeGroup (Fin n)) → Prop
  | inv (r : Fin n → FreeGroup (Fin n)) (i : Fin n) :
      Move r (Function.update r i (r i)⁻¹)
  | mul (r : Fin n → FreeGroup (Fin n)) (i j : Fin n) (hij : i ≠ j) :
      Move r (Function.update r i (r i * r j))
  | conj (r : Fin n → FreeGroup (Fin n)) (i : Fin n) (w : FreeGroup (Fin n)) :
      Move r (Function.update r i (w * r i * w⁻¹))

/--
Two $n$-tuples of relators $r$ and $s$ in the free group on $n$ generators are Andrews–Curtis
equivalent if $r$ can be transformed into $s$ by a finite sequence of elementary
Andrews–Curtis moves.
-/
def ACEquivalent {n : ℕ} (r s : Fin n → FreeGroup (Fin n)) : Prop :=
  Relation.ReflTransGen Move r s

/--
**Andrews–Curtis conjecture.** Every balanced presentation of the trivial group can be
transformed into a trivial presentation by a sequence of Nielsen transformations on the relators
together with conjugations of relators.

Precisely: for every $n$ and every $n$-tuple $(r_1, \dots, r_n)$ of elements of the free group
on $x_1, \dots, x_n$ such that the balanced presentation
$\langle x_1, \dots, x_n \mid r_1, \dots, r_n \rangle$ presents the trivial group, the tuple
$(r_1, \dots, r_n)$ can be transformed into the trivial presentation $(x_1, \dots, x_n)$ by a
finite sequence of elementary Andrews–Curtis moves (replace some $r_i$ by $r_i^{-1}$, by
$r_i r_j$ with $j \ne i$, or by $w r_i w^{-1}$ for a word $w$).
-/
@[category research open, AMS 20 57]
theorem andrews_curtis_conjecture (n : ℕ) (r : Fin n → FreeGroup (Fin n))
    (hr : Subsingleton (PresentedGroup (Set.range r))) :
    ACEquivalent r FreeGroup.of := by
  sorry

/-- For `n = 0` there is only one (empty) presentation, so the conjecture holds trivially. -/
@[category test, AMS 20]
theorem andrews_curtis_conjecture_zero (r : Fin 0 → FreeGroup (Fin 0)) :
    ACEquivalent r FreeGroup.of := by
  rw [Subsingleton.elim r FreeGroup.of]
  exact Relation.ReflTransGen.refl

/-- The presentation `⟨x | x⁻¹⟩` is turned into the trivial presentation `⟨x | x⟩` by a single
inversion move. -/
@[category test, AMS 20]
theorem move_inv_of : Move (fun _ : Fin 1 => (FreeGroup.of 0)⁻¹) FreeGroup.of := by
  convert Move.inv (fun _ : Fin 1 => (FreeGroup.of 0)⁻¹) 0 using 1
  ext i
  fin_cases i
  simp

/-- Replacing the relator `r i` by an element `x` of the normal closure of the relators does not
change the normal closure, provided `r i` lies in the normal closure of the new relators. -/
@[category API, AMS 20]
lemma normalClosure_range_update_eq {n : ℕ} (r : Fin n → FreeGroup (Fin n)) (i : Fin n)
    {x : FreeGroup (Fin n)} (hx : x ∈ Subgroup.normalClosure (Set.range r))
    (hr : r i ∈ Subgroup.normalClosure (Set.range (Function.update r i x))) :
    Subgroup.normalClosure (Set.range r) =
      Subgroup.normalClosure (Set.range (Function.update r i x)) := by
  apply le_antisymm <;> apply Subgroup.normalClosure_le_normal <;> rintro _ ⟨k, rfl⟩
  · rcases eq_or_ne k i with rfl | hk
    · exact hr
    · exact Subgroup.subset_normalClosure ⟨k, Function.update_of_ne hk x r⟩
  · rcases eq_or_ne k i with rfl | hk
    · simpa using hx
    · rw [Function.update_of_ne hk]
      exact Subgroup.subset_normalClosure (Set.mem_range_self k)

/-- An elementary Andrews–Curtis move does not change the normal closure of the relators, and
hence does not change the presented group. -/
@[category API, AMS 20]
theorem Move.normalClosure_range_eq {n : ℕ} {r s : Fin n → FreeGroup (Fin n)} (h : Move r s) :
    Subgroup.normalClosure (Set.range r) = Subgroup.normalClosure (Set.range s) := by
  have mem : ∀ (t : Fin n → FreeGroup (Fin n)) k, t k ∈ Subgroup.normalClosure (Set.range t) :=
    fun t k => Subgroup.subset_normalClosure (Set.mem_range_self k)
  cases h with
  | inv i =>
    refine normalClosure_range_update_eq r i (inv_mem (mem r i)) ?_
    simpa using inv_mem (mem (Function.update r i (r i)⁻¹) i)
  | mul i j hij =>
    refine normalClosure_range_update_eq r i (mul_mem (mem r i) (mem r j)) ?_
    have h1 := mem (Function.update r i (r i * r j)) i
    have h2 := mem (Function.update r i (r i * r j)) j
    rw [Function.update_self] at h1
    rw [Function.update_of_ne hij.symm] at h2
    simpa using mul_mem h1 (inv_mem h2)
  | conj i w =>
    refine normalClosure_range_update_eq r i
      (Subgroup.Normal.conj_mem inferInstance _ (mem r i) w) ?_
    have h1 := mem (Function.update r i (w * r i * w⁻¹)) i
    rw [Function.update_self] at h1
    simpa [mul_assoc] using Subgroup.Normal.conj_mem inferInstance _ h1 w⁻¹

/-- Andrews–Curtis equivalent tuples of relators have the same normal closure, and hence present
the same group. -/
@[category API, AMS 20]
theorem ACEquivalent.normalClosure_range_eq {n : ℕ} {r s : Fin n → FreeGroup (Fin n)}
    (h : ACEquivalent r s) :
    Subgroup.normalClosure (Set.range r) = Subgroup.normalClosure (Set.range s) := by
  induction h with
  | refl => rfl
  | tail _ hst ih => exact ih.trans hst.normalClosure_range_eq

/-- The converse of the Andrews–Curtis conjecture: a balanced presentation that is
Andrews–Curtis equivalent to the trivial presentation presents the trivial group. -/
@[category API, AMS 20]
theorem ACEquivalent.subsingleton_presentedGroup {n : ℕ} {r : Fin n → FreeGroup (Fin n)}
    (h : ACEquivalent r FreeGroup.of) : Subsingleton (PresentedGroup (Set.range r)) := by
  have : Subgroup.normalClosure (Set.range r) = ⊤ := by
    rw [h.normalClosure_range_eq, eq_top_iff, ← FreeGroup.closure_range_of (Fin n)]
    exact Subgroup.closure_le_normalClosure
  unfold PresentedGroup
  rw [this]
  exact QuotientGroup.subsingleton_quotient_top

end AndrewsCurtisConjecture
