/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Dixmier conjecture

The Dixmier conjecture: any endomorphism of the Weyl algebras $A_1$ and $A_2$ is an automorphism.

Here $k$ is a field of characteristic zero and the $n$-th Weyl algebra $A_n$ is the unital
associative $k$-algebra with generators $x_1, \dots, x_n, \partial_1, \dots, \partial_n$ and
relations
$$[x_i, x_j] = 0, \quad [\partial_i, \partial_j] = 0, \quad [\partial_i, x_j] = \delta_{ij}.$$
An endomorphism is a unital $k$-algebra homomorphism $A_n \to A_n$, and it is an automorphism
when it is bijective.

The case $n = 1$ is the problem posed by Dixmier in 1968. The case $n = 2$ is a case of the
generalized Dixmier conjecture $DC_n$. By Tsuchimoto and Belov-Kanel–Kontsevich, $DC_n$ implies
the Jacobian conjecture $JC_n$ in $n$ variables, and $JC_{2n}$ implies $DC_n$. The Jacobian
conjecture is false in three variables, so $DC_n$ is false for all $n \geq 3$, and the conjecture
is only stated for $A_1$ and $A_2$.

The Weyl algebra is not in Mathlib, so this file defines it as the quotient of the free algebra
on the generators $x_i$, $\partial_i$ by the relations above.

*References:*
- [Wikipedia, *List of unsolved problems in mathematics*](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics)
- [Wikipedia, *Dixmier conjecture*](https://en.wikipedia.org/wiki/Dixmier_conjecture)
- [J. Dixmier, *Sur les algèbres de Weyl*, Bull. Soc. Math. France 96 (1968), 209–242](http://www.numdam.org/item?id=BSMF_1968__96__209_0)
- [A. Belov-Kanel, M. Kontsevich, *The Jacobian conjecture is stably equivalent to the Dixmier conjecture*](https://arxiv.org/abs/math/0512171)
- [A. Zheglov, *The Conjecture of Dixmier for the first Weyl algebra is true*](https://arxiv.org/abs/2410.06959)
-/

namespace DixmierConjecture

section WeylAlgebra

variable (k : Type*) [CommRing k] (σ : Type*)

namespace WeylAlgebra

open FreeAlgebra in
/-- The defining relations of the Weyl algebra, as a relation on the free algebra with generators
`Sum.inl i` (the coordinate $x_i$) and `Sum.inr i` (the partial derivative $\partial_i$). -/
inductive Rel : FreeAlgebra k (σ ⊕ σ) → FreeAlgebra k (σ ⊕ σ) → Prop
  /-- The coordinates commute: $x_i x_j = x_j x_i$. -/
  | x_mul_x (i j : σ) : Rel (ι k (.inl i) * ι k (.inl j)) (ι k (.inl j) * ι k (.inl i))
  /-- The partial derivatives commute: $\partial_i \partial_j = \partial_j \partial_i$. -/
  | d_mul_d (i j : σ) : Rel (ι k (.inr i) * ι k (.inr j)) (ι k (.inr j) * ι k (.inr i))
  /-- The canonical commutation relation: $\partial_i x_i = x_i \partial_i + 1$. -/
  | d_mul_x_self (i : σ) : Rel (ι k (.inr i) * ι k (.inl i)) (ι k (.inl i) * ι k (.inr i) + 1)
  /-- Distinct indices commute: $\partial_i x_j = x_j \partial_i$ for $i \ne j$. -/
  | d_mul_x_of_ne {i j : σ} (h : i ≠ j) :
    Rel (ι k (.inr i) * ι k (.inl j)) (ι k (.inl j) * ι k (.inr i))

end WeylAlgebra

/-- The Weyl algebra over `k` with coordinates and partial derivatives indexed by `σ`: the unital
associative `k`-algebra generated by $x_i$, $\partial_i$ ($i \in \sigma$) subject to
$[x_i, x_j] = 0$, $[\partial_i, \partial_j] = 0$ and $[\partial_i, x_j] = \delta_{ij}$.
The $n$-th Weyl algebra $A_n$ is `WeylAlgebra k (Fin n)`. -/
def WeylAlgebra := RingQuot (WeylAlgebra.Rel k σ)

namespace WeylAlgebra

instance : Ring (WeylAlgebra k σ) := RingQuot.instRing _

instance : Algebra k (WeylAlgebra k σ) := RingQuot.instAlgebra _

variable {σ}

/-- The coordinate $x_i$ in the Weyl algebra. -/
def x (i : σ) : WeylAlgebra k σ := RingQuot.mkAlgHom k (Rel k σ) (FreeAlgebra.ι k (.inl i))

/-- The partial derivative $\partial_i$ in the Weyl algebra. -/
def d (i : σ) : WeylAlgebra k σ := RingQuot.mkAlgHom k (Rel k σ) (FreeAlgebra.ι k (.inr i))

@[category API, AMS 16]
lemma x_mul_x (i j : σ) : x k i * x k j = x k j * x k i := by
  simpa [x] using RingQuot.mkAlgHom_rel k (Rel.x_mul_x (k := k) i j)

@[category API, AMS 16]
lemma d_mul_d (i j : σ) : d k i * d k j = d k j * d k i := by
  simpa [d] using RingQuot.mkAlgHom_rel k (Rel.d_mul_d (k := k) i j)

@[category API, AMS 16]
lemma d_mul_x_self (i : σ) : d k i * x k i = x k i * d k i + 1 := by
  simpa [x, d] using RingQuot.mkAlgHom_rel k (Rel.d_mul_x_self (k := k) i)

@[category API, AMS 16]
lemma d_mul_x_of_ne {i j : σ} (h : i ≠ j) : d k i * x k j = x k j * d k i := by
  simpa [x, d] using RingQuot.mkAlgHom_rel k (Rel.d_mul_x_of_ne (k := k) h)

/-- The canonical commutation relation $[\partial_i, x_i] = 1$. -/
@[category API, AMS 16]
lemma d_mul_x_sub_x_mul_d (i : σ) : d k i * x k i - x k i * d k i = 1 := by
  rw [d_mul_x_self, add_sub_cancel_left]

/-- The commutation relation $[\partial_i, x_j] = \delta_{ij}$. -/
@[category API, AMS 16]
lemma d_mul_x_sub_x_mul_d_eq_ite [DecidableEq σ] (i j : σ) :
    d k i * x k j - x k j * d k i = if i = j then 1 else 0 := by
  split_ifs with h
  · subst h
    exact d_mul_x_sub_x_mul_d k i
  · rw [d_mul_x_of_ne k h, sub_self]

variable (σ) in
/-- The standard representation of the Weyl algebra by differential operators with polynomial
coefficients: $x_i$ acts on `MvPolynomial σ k` as multiplication by `X i`, and $\partial_i$ acts
as `pderiv i`. -/
noncomputable def toDiffOp : WeylAlgebra k σ →ₐ[k] Module.End k (MvPolynomial σ k) :=
  RingQuot.liftAlgHom k ⟨FreeAlgebra.lift k <| Sum.elim
      (fun i ↦ LinearMap.mulLeft k (MvPolynomial.X i))
      (fun i ↦ (MvPolynomial.pderiv i).toLinearMap), by
    intro a b h
    induction h with
    | x_mul_x i j =>
      refine LinearMap.ext fun p ↦ ?_
      simp [mul_left_comm]
    | d_mul_d i j =>
      refine LinearMap.ext fun p ↦ ?_
      have : ⁅MvPolynomial.pderiv (R := k) i, MvPolynomial.pderiv j⁆ = 0 :=
        MvPolynomial.derivation_ext fun l ↦ by
          rw [Derivation.commutator_apply]
          obtain rfl | hli := eq_or_ne l i <;> obtain rfl | hlj := eq_or_ne l j <;> simp [*]
      simpa [Derivation.commutator_apply, sub_eq_zero] using DFunLike.congr_fun this p
    | d_mul_x_self i =>
      refine LinearMap.ext fun p ↦ ?_
      simp [add_comm]
    | d_mul_x_of_ne h =>
      refine LinearMap.ext fun p ↦ ?_
      simp [MvPolynomial.pderiv_X_of_ne h.symm]⟩

@[category API, AMS 16]
lemma toDiffOp_x (i : σ) : toDiffOp k σ (x k i) = LinearMap.mulLeft k (MvPolynomial.X i) :=
  (RingQuot.liftAlgHom_mkAlgHom_apply _ _ _ _).trans (FreeAlgebra.lift_ι_apply _ _)

@[category API, AMS 16]
lemma toDiffOp_d (i : σ) : toDiffOp k σ (d k i) = (MvPolynomial.pderiv i).toLinearMap :=
  (RingQuot.liftAlgHom_mkAlgHom_apply _ _ _ _).trans (FreeAlgebra.lift_ι_apply _ _)

/-- The Weyl algebra over a nontrivial ring is nontrivial, so the relations do not collapse
and the Dixmier conjecture is not trivially true. -/
@[category API, AMS 16]
instance [Nontrivial k] : Nontrivial (WeylAlgebra k σ) :=
  (toDiffOp k σ).toRingHom.domain_nontrivial

/-- In a Weyl algebra over a nontrivial ring, $\partial_i$ and $x_i$ do not commute. -/
@[category test, AMS 16]
lemma d_mul_x_ne_x_mul_d [Nontrivial k] (i : σ) : d k i * x k i ≠ x k i * d k i := by
  rw [Ne, ← sub_eq_zero, d_mul_x_sub_x_mul_d]
  exact one_ne_zero

end WeylAlgebra

end WeylAlgebra

section Conjecture

variable {k : Type*} [Field k] [CharZero k]

/-- The **Dixmier conjecture** for the first Weyl algebra $A_1$ (Dixmier's original 1968 problem,
$DC_1$): for any field $k$ of characteristic zero, every unital $k$-algebra endomorphism of
$A_1 = k\langle x, \partial \rangle / ([\partial, x] = 1)$ is an automorphism, i.e. is bijective.

A proof was announced by Zheglov in 2024, but the problem is still regarded as open. -/
@[category research open, AMS 14 16]
theorem dixmier_conjecture.parts.i (f : WeylAlgebra k (Fin 1) →ₐ[k] WeylAlgebra k (Fin 1)) :
    Function.Bijective f := by
  sorry

/-- The **Dixmier conjecture** for the second Weyl algebra $A_2$ (the generalized Dixmier conjecture
$DC_2$): for any field $k$ of characteristic zero, every unital $k$-algebra endomorphism of
$A_2$, the $k$-algebra with generators $x_1, x_2, \partial_1, \partial_2$ and relations
$[\partial_i, x_j] = \delta_{ij}$, $[x_i, x_j] = 0$, $[\partial_i, \partial_j] = 0$,
is an automorphism, i.e. is bijective.

By Tsuchimoto and Belov-Kanel–Kontsevich, $DC_2$ implies the Jacobian conjecture $JC_2$, and
$JC_4$ implies $DC_2$. -/
@[category research open, AMS 14 16]
theorem dixmier_conjecture.parts.ii (f : WeylAlgebra k (Fin 2) →ₐ[k] WeylAlgebra k (Fin 2)) :
    Function.Bijective f := by
  sorry

end Conjecture

end DixmierConjecture
