/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Fröberg conjecture

The Fröberg conjecture predicts the Hilbert series of the quotient of
$\mathbb{C}[x_1, \ldots, x_n]$ by the ideal generated by generic forms of prescribed degrees.

*References:*
* [Wikipedia](https://en.wikipedia.org/wiki/Fr%C3%B6berg_conjecture)
* [Wikipedia, List of unsolved problems in mathematics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics)
* R. Fröberg, *An inequality for Hilbert series of graded algebras*,
  Math. Scand. 56 (1985), 117–144.
  [doi:10.7146/math.scand.a-12092](https://doi.org/10.7146/math.scand.a-12092)
-/

namespace FrobergConjecture

section HilbertSeries

open MvPolynomial

variable {σ K : Type*} [Field K]

/-- The Hilbert function of the graded algebra $K[x_i : i \in σ] / I$: its value at `d` is the
dimension of the image in the quotient of the space of homogeneous polynomials of degree `d`
(this image is finite-dimensional when `σ` is finite). When `I` is a homogeneous ideal, this is
the dimension of the degree `d` component of the quotient. -/
noncomputable def hilbertFunction (I : Ideal (MvPolynomial σ K)) (d : ℕ) : ℕ :=
  Module.finrank K ((homogeneousSubmodule σ K d).map (Ideal.Quotient.mkₐ K I).toLinearMap)

/-- The Hilbert series $\sum_{d \ge 0} \dim_K (K[x_i : i \in σ] / I)_d \, t^d$ of the graded
algebra $K[x_i : i \in σ] / I$, as a formal power series with integer coefficients. -/
noncomputable def hilbertSeries (I : Ideal (MvPolynomial σ K)) : PowerSeries ℤ :=
  PowerSeries.mk fun d => (hilbertFunction I d : ℤ)

@[category test, AMS 13]
theorem hilbertFunction_top (d : ℕ) :
    hilbertFunction (⊤ : Ideal (MvPolynomial σ K)) d = 0 := by
  have : Subsingleton (MvPolynomial σ K ⧸ (⊤ : Ideal (MvPolynomial σ K))) :=
    Ideal.Quotient.subsingleton_iff.mpr rfl
  exact Module.finrank_zero_of_subsingleton

@[category test, AMS 13]
theorem hilbertSeries_top : hilbertSeries (⊤ : Ideal (MvPolynomial σ K)) = 0 := by
  ext d
  simp [hilbertSeries, hilbertFunction_top]

end HilbertSeries

section Series

open PowerSeries

/-- The formal power series
$$\frac{(1 - t^{a_1})(1 - t^{a_2}) \cdots (1 - t^{a_k})}{(1 - t)^n}
  = (1 + t + t^2 + \cdots)^n (1 - t^{a_1})(1 - t^{a_2}) \cdots (1 - t^{a_k})$$
with integer coefficients, where `n` is the number of variables and `a 0, …, a (k - 1)` are the
degrees of the forms. -/
noncomputable def frobergSeries (n : ℕ) {k : ℕ} (a : Fin k → ℕ) : PowerSeries ℤ :=
  (∏ i, (1 - X ^ a i)) * (invOneSubPow ℤ n : ℤ⟦X⟧)

open scoped Classical in
/-- The power series `f` truncated at its first negative coefficient: the coefficient of `t ^ d`
is left unchanged if all the coefficients of `t ^ e` with `e ≤ d` are nonnegative, and it is
replaced by `0` otherwise. -/
noncomputable def truncateAtFirstNegative (f : PowerSeries ℤ) : PowerSeries ℤ :=
  PowerSeries.mk fun d => if ∃ e ≤ d, coeff e f < 0 then 0 else coeff d f

@[category test, AMS 13]
theorem frobergSeries_zero_forms (n : ℕ) :
    frobergSeries n (Fin.elim0 : Fin 0 → ℕ) = (invOneSubPow ℤ n : ℤ⟦X⟧) := by
  simp [frobergSeries]

/-- The series for one form of degree `2` in one variable is $(1 - t^2) / (1 - t) = 1 + t$. -/
@[category test, AMS 13]
theorem frobergSeries_one_two : frobergSeries 1 ![2] = 1 + X := by
  have h1 : (invOneSubPow ℤ 1 : ℤ⟦X⟧) * (1 - X) = 1 := by
    rw [invOneSubPow_val_eq_mk_sub_one_add_choose_of_pos _ _ one_pos]
    simpa using mk_one_mul_one_sub_eq_one (S := ℤ)
  have h2 : frobergSeries 1 ![2] * (1 - X) = (1 + X) * (1 - X) := by
    simp only [frobergSeries, Fin.prod_univ_one, Matrix.cons_val_fin_one]
    rw [mul_assoc, h1]
    ring
  refine mul_right_cancel₀ (fun h => ?_) h2
  have := congrArg constantCoeff h
  simp at this

/-- The series for two forms of degree `2` in one variable is
$(1 - t^2)^2 / (1 - t) = 1 + t - t^2 - t^3$. -/
@[category test, AMS 13]
theorem frobergSeries_one_two_two : frobergSeries 1 ![2, 2] = 1 + X - X ^ 2 - X ^ 3 := by
  have h1 : (invOneSubPow ℤ 1 : ℤ⟦X⟧) * (1 - X) = 1 := by
    rw [invOneSubPow_val_eq_mk_sub_one_add_choose_of_pos _ _ one_pos]
    simpa using mk_one_mul_one_sub_eq_one (S := ℤ)
  have h2 : frobergSeries 1 ![2, 2] * (1 - X) = (1 + X - X ^ 2 - X ^ 3) * (1 - X) := by
    simp only [frobergSeries, Fin.prod_univ_two, Matrix.cons_val_zero, Matrix.cons_val_one]
    rw [mul_assoc, h1]
    ring
  refine mul_right_cancel₀ (fun h => ?_) h2
  have := congrArg constantCoeff h
  simp at this

@[category test, AMS 13]
theorem truncateAtFirstNegative_of_nonneg {f : PowerSeries ℤ} (hf : ∀ d, 0 ≤ coeff d f) :
    truncateAtFirstNegative f = f := by
  ext d
  have : ¬ ∃ e ≤ d, coeff e f < 0 := fun ⟨e, _, he⟩ => (hf e).not_gt he
  simp [truncateAtFirstNegative, this]

/-- The series $(1 - t^2)^2 / (1 - t) = 1 + t - t^2 - t^3$ truncated at its first negative
coefficient is $1 + t$, the Hilbert series of $\mathbb{C}[x] / (x^2)$. -/
@[category test, AMS 13]
theorem truncateAtFirstNegative_frobergSeries_one_two_two :
    truncateAtFirstNegative (frobergSeries 1 ![2, 2]) = 1 + X := by
  ext d
  rw [frobergSeries_one_two_two]
  simp only [truncateAtFirstNegative, coeff_mk, map_add, map_sub, coeff_one, coeff_X,
    coeff_X_pow]
  rcases lt_trichotomy d 1 with hd | rfl | hd
  · obtain rfl : d = 0 := by omega
    simp
  · simp only [if_neg (by omega : ¬ ∃ e ≤ 1, (if e = 0 then (1 : ℤ) else 0) +
      (if e = 1 then 1 else 0) - (if e = 2 then 1 else 0) - (if e = 3 then 1 else 0) < 0)]
    simp
  · have : ∃ e ≤ d, (if e = 0 then (1 : ℤ) else 0) + (if e = 1 then 1 else 0) -
        (if e = 2 then 1 else 0) - (if e = 3 then 1 else 0) < 0 :=
      ⟨2, by omega, by simp⟩
    rw [if_pos this]
    have h0 : d ≠ 0 := by omega
    have h1 : d ≠ 1 := by omega
    simp [h0, h1]

end Series

section Generic

open MvPolynomial

/-- A property `p` of `k`-tuples `g` of homogeneous polynomials in `n` variables over `ℂ`, of
degrees `a 0, …, a (k - 1)`, holds for *generic* such tuples if it holds on a nonempty
Zariski-open subset of the affine space of all such tuples. Since `ℂ` is infinite, this means
that there is a nonzero polynomial `P` in the coefficients of the forms (one indeterminate for
each `i : Fin k` and each monomial of degree `a i`) such that `p g` holds for every tuple `g` of
forms of the given degrees at whose coefficients `P` does not vanish. -/
def HoldsForGenericForms (n : ℕ) {k : ℕ} (a : Fin k → ℕ)
    (p : (Fin k → MvPolynomial (Fin n) ℂ) → Prop) : Prop :=
  ∃ P : MvPolynomial (Σ i : Fin k, {m : Fin n →₀ ℕ // m.degree = a i}) ℂ, P ≠ 0 ∧
    ∀ g : Fin k → MvPolynomial (Fin n) ℂ, (∀ i, (g i).IsHomogeneous (a i)) →
      eval (fun x => coeff x.2.1 (g x.1)) P ≠ 0 → p g

/-- A property that holds for all tuples of forms holds for generic tuples of forms. -/
@[category test, AMS 14]
theorem HoldsForGenericForms.of_forall (n : ℕ) {k : ℕ} (a : Fin k → ℕ)
    {p : (Fin k → MvPolynomial (Fin n) ℂ) → Prop} (hp : ∀ g, p g) :
    HoldsForGenericForms n a p :=
  ⟨1, one_ne_zero, fun g _ _ => hp g⟩

/-- A property that holds for generic tuples of forms holds for at least one tuple of forms
of the given degrees. In particular the hypothesis in `HoldsForGenericForms` is never vacuous:
every point of the affine space of coefficients is realised by a tuple of forms. -/
@[category test, AMS 14]
theorem HoldsForGenericForms.exists (n : ℕ) {k : ℕ} (a : Fin k → ℕ)
    {p : (Fin k → MvPolynomial (Fin n) ℂ) → Prop} (hp : HoldsForGenericForms n a p) :
    ∃ g : Fin k → MvPolynomial (Fin n) ℂ, (∀ i, (g i).IsHomogeneous (a i)) ∧ p g := by
  classical
  obtain ⟨P, hP, h⟩ := hp
  obtain ⟨c, hc⟩ : ∃ c, eval c P ≠ 0 := by
    by_contra! hc
    exact hP (MvPolynomial.funext fun c => by simp [hc c])
  -- the finset of monomials of degree `d` in `n` variables
  set S : ℕ → Finset (Fin n →₀ ℕ) := fun d => Finset.finsuppAntidiag Finset.univ d
    with hS_def
  have hS {d : ℕ} {m : Fin n →₀ ℕ} : m ∈ S d ↔ m.degree = d := by
    simp [hS_def, Finsupp.degree_eq_sum]
  -- the tuple of forms with coefficients `c`
  set g : Fin k → MvPolynomial (Fin n) ℂ := fun i =>
    ∑ m ∈ S (a i), monomial m (if h : m.degree = a i then c ⟨i, m, h⟩ else 0) with hg_def
  have hg : ∀ i, (g i).IsHomogeneous (a i) := fun i =>
    IsHomogeneous.sum _ _ _ fun m hm => isHomogeneous_monomial _ (hS.mp hm)
  have hcoeff : (fun x : Σ i : Fin k, {m : Fin n →₀ ℕ // m.degree = a i} =>
      coeff x.2.1 (g x.1)) = c := by
    funext ⟨i, m, hm⟩
    simp [hg_def, coeff_sum, coeff_monomial, Finset.sum_ite_eq', hS.mpr hm, hm]
  exact ⟨g, hg, h g hg (hcoeff ▸ hc)⟩

end Generic

/-- **Fröberg conjecture** (Fröberg 1985, p. 120).
Let $g_1, g_2, \ldots, g_k \in \mathbb{C}[x_1, x_2, \ldots, x_n]$ be generic homogeneous
polynomials of degrees $a_1, a_2, \ldots, a_k$ respectively. Then the Hilbert series of
$\mathbb{C}[x_1, x_2, \ldots, x_n] / \langle g_1, g_2, \ldots, g_k \rangle$ is
$$(1 + t + t^2 + \cdots)^n (1 - t^{a_1})(1 - t^{a_2}) \cdots (1 - t^{a_k})
  = \frac{(1 - t^{a_1})(1 - t^{a_2}) \cdots (1 - t^{a_k})}{(1 - t)^n},$$
truncated at its first negative term.

Here "generic" means that, for every `n`, `k` and degrees `a`, the conclusion holds for all
tuples of forms in a nonempty Zariski-open subset of the affine space of `k`-tuples of forms of
degrees `a 0, …, a (k - 1)`; see `FrobergConjecture.HoldsForGenericForms`. -/
@[category research open, AMS 13 14]
theorem froberg_conjecture (n k : ℕ) (a : Fin k → ℕ) :
    HoldsForGenericForms n a fun g =>
      hilbertSeries (Ideal.span (Set.range g)) = truncateAtFirstNegative (frobergSeries n a) := by
  sorry

end FrobergConjecture
