/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Nakai conjecture

The Nakai conjecture (Y. Nakai, 1961) states that if $V$ is a complex algebraic variety
whose ring of differential operators is generated by the derivations it contains, then $V$
is smooth. The converse is a theorem of Grothendieck.

For an affine variety $V$ with coordinate ring $R$ (a reduced, finitely generated
$\mathbb{C}$-algebra), the ring of differential operators is Grothendieck's ring
$D(R) = \bigcup_n D^n(R) \subseteq \operatorname{End}_{\mathbb{C}}(R)$, where
$D^0(R) = R$ (acting by multiplication) and $\theta \in D^{n+1}(R)$ iff
$[\theta, a] \in D^n(R)$ for all $a \in R$. The hypothesis of the conjecture is that $D(R)$
is generated, as a ring, by $R = D^0(R)$ together with the derivations
$\operatorname{Der}_{\mathbb{C}}(R)$, that is,
$D(R) = R\langle \operatorname{Der}_{\mathbb{C}}(R) \rangle$.
(Generation by derivations alone, without $R$, is impossible unless $R = \mathbb{C}$, since every
product of derivations kills $1$.) Over $\mathbb{C}$, smoothness of $V$ is the same as $R$ being a
smooth $\mathbb{C}$-algebra, or equivalently a regular ring.

The variety is only required to be reduced, not irreducible, as in the literature; for instance
the known Stanley–Reisner case is reducible.

*References:*
- [Wikipedia, Nakai conjecture](https://en.wikipedia.org/wiki/Nakai_conjecture)
- [Wikipedia, List of unsolved problems in
  mathematics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics)
- Y. Nakai, *On the theory of differentials in commutative rings*,
  J. Math. Soc. Japan 13 (1961), 63–84.
- K. R. Mount, O. E. Villamayor, *On a conjecture of Y. Nakai*,
  Osaka J. Math. 10 (1973), 325–327.
- A. Schreiner, *On a conjecture of Nakai*, Arch. Math. 62 (1994), 506–512.
-/

namespace NakaiConjecture

section DifferentialOperators

variable (k R : Type*) [CommRing k] [CommRing R] [Algebra k R]

/-- `IsDiffOp k R n θ` says that the `k`-linear endomorphism `θ` of the commutative `k`-algebra
`R` is a (Grothendieck) differential operator of order at most `n`.

The definition is inductive: `θ` has order at most `0` if it commutes with every multiplication
operator `LinearMap.mulLeft k a`, `a : R` (such `θ` are exactly the multiplication operators);
and `θ` has order at most `n + 1` if the commutator `⁅θ, LinearMap.mulLeft k a⁆` has order at
most `n` for every `a : R`. -/
def IsDiffOp : ℕ → Module.End k R → Prop
  | 0, θ => ∀ a : R, ⁅θ, LinearMap.mulLeft k a⁆ = 0
  | n + 1, θ => ∀ a : R, IsDiffOp n ⁅θ, LinearMap.mulLeft k a⁆

/-- The ring of differential operators `D(R)` of the commutative `k`-algebra `R`, as a subset of
`Module.End k R`: the `k`-linear endomorphisms of `R` that are differential operators of some
finite order. -/
def diffOps : Set (Module.End k R) :=
  {θ | ∃ n, IsDiffOp k R n θ}

/-- The subset of `Module.End k R` consisting of the multiplication operators
`LinearMap.mulLeft k a`, `a : R`, together with the `k`-derivations of `R`. The `k`-subalgebra
of `Module.End k R` generated by this set is the ring `R⟨Der_k(R)⟩` of operators generated by
`R` and its derivations. -/
def mulLeftsAndDerivations : Set (Module.End k R) :=
  Set.range (LinearMap.mulLeft k : R → Module.End k R) ∪
    Set.range (fun D : Derivation k R R ↦ D.toLinearMap)

variable {k R}

@[category API, AMS 13]
theorem isDiffOp_zero_iff (θ : Module.End k R) :
    IsDiffOp k R 0 θ ↔ ∀ a : R, ⁅θ, LinearMap.mulLeft k a⁆ = 0 :=
  Iff.rfl

@[category API, AMS 13]
theorem isDiffOp_succ_iff (n : ℕ) (θ : Module.End k R) :
    IsDiffOp k R (n + 1) θ ↔ ∀ a : R, IsDiffOp k R n ⁅θ, LinearMap.mulLeft k a⁆ :=
  Iff.rfl

/-- The zero operator has order at most `n` for every `n`. -/
@[category API, AMS 13]
theorem isDiffOp_zero_op (n : ℕ) : IsDiffOp k R n (0 : Module.End k R) := by
  induction n with
  | zero => intro a; simp
  | succ n ih => intro a; simpa using ih

/-- A differential operator of order at most `n` has order at most `n + 1`. -/
@[category API, AMS 13]
theorem IsDiffOp.succ {n : ℕ} {θ : Module.End k R} (h : IsDiffOp k R n θ) :
    IsDiffOp k R (n + 1) θ := by
  induction n generalizing θ with
  | zero => intro a; rw [h a]; exact isDiffOp_zero_op 0
  | succ n ih => intro a; exact ih (h a)

/-- Multiplication by an element of `R` is a differential operator of order `0`. -/
@[category API, AMS 13]
theorem isDiffOp_zero_mulLeft (a : R) : IsDiffOp k R 0 (LinearMap.mulLeft k a) := by
  intro b
  ext c
  simp [Ring.lie_def, mul_left_comm]

/-- The differential operators of order `0` are exactly the multiplication operators. -/
@[category API, AMS 13]
theorem isDiffOp_zero_iff_exists_mulLeft (θ : Module.End k R) :
    IsDiffOp k R 0 θ ↔ ∃ a : R, θ = LinearMap.mulLeft k a := by
  refine ⟨fun h ↦ ⟨θ 1, ?_⟩, ?_⟩
  · ext b
    have := LinearMap.congr_fun (h b) 1
    simpa [Ring.lie_def, mul_comm, sub_eq_zero] using this
  · rintro ⟨a, rfl⟩
    exact isDiffOp_zero_mulLeft a

/-- The commutator of a derivation `D` with multiplication by `a` is multiplication by `D a`. -/
@[category API, AMS 13]
theorem lie_derivation_mulLeft (D : Derivation k R R) (a : R) :
    ⁅D.toLinearMap, LinearMap.mulLeft k a⁆ = LinearMap.mulLeft k (D a) := by
  ext b
  simp [Ring.lie_def, D.leibniz, mul_comm]

/-- A derivation is a differential operator of order at most `1`. -/
@[category API, AMS 13]
theorem isDiffOp_one_derivation (D : Derivation k R R) : IsDiffOp k R 1 D.toLinearMap := by
  intro a
  rw [lie_derivation_mulLeft]
  exact isDiffOp_zero_mulLeft _

/-- The multiplication operators and the derivations are differential operators. -/
@[category API, AMS 13]
theorem mulLeftsAndDerivations_subset_diffOps : mulLeftsAndDerivations k R ⊆ diffOps k R := by
  rintro θ (⟨a, rfl⟩ | ⟨D, rfl⟩)
  · exact ⟨0, isDiffOp_zero_mulLeft a⟩
  · exact ⟨1, isDiffOp_one_derivation D⟩

/-- Every `k`-linear endomorphism of `k` is a multiplication operator. -/
@[category API, AMS 13]
theorem end_self_eq_mulLeft (θ : Module.End k k) : θ = LinearMap.mulLeft k (θ 1) := by
  ext
  simp

/-- Sanity check: for the base ring itself (the coordinate ring of a point), the ring of
differential operators is generated by the multiplication operators and the derivations. -/
@[category test, AMS 13]
theorem diffOps_self_eq_adjoin_mulLeftsAndDerivations :
    diffOps k k = (Algebra.adjoin k (mulLeftsAndDerivations k k) : Set (Module.End k k)) := by
  apply Set.eq_of_subset_of_subset
  · intro θ _
    rw [end_self_eq_mulLeft θ]
    exact Algebra.subset_adjoin (Or.inl ⟨_, rfl⟩)
  · intro θ _
    exact ⟨0, end_self_eq_mulLeft θ ▸ isDiffOp_zero_mulLeft (θ 1)⟩

end DifferentialOperators

/-- **Nakai conjecture.** Let $V$ be a complex (affine) algebraic variety with coordinate ring
$R$, i.e. $R$ is a reduced, finitely generated $\mathbb{C}$-algebra. If the ring of differential
operators $D(R)$ of $V$ is generated by the derivations it contains, i.e. $D(R)$ is the
$\mathbb{C}$-subalgebra of $\operatorname{End}_{\mathbb{C}}(R)$ generated by the multiplication
operators $R = D^0(R)$ and the derivations $\operatorname{Der}_{\mathbb{C}}(R)$, then $V$ is
smooth, i.e. $R$ is a smooth $\mathbb{C}$-algebra. -/
@[category research open, AMS 13 14]
theorem nakai_conjecture (R : Type*) [CommRing R] [Algebra ℂ R] [Algebra.FiniteType ℂ R]
    [IsReduced R]
    (h : diffOps ℂ R =
      (Algebra.adjoin ℂ (mulLeftsAndDerivations ℂ R) : Set (Module.End ℂ R))) :
    Algebra.Smooth ℂ R := by
  sorry

end NakaiConjecture
