/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Andrews–Curtis conjecture

The Andrews–Curtis conjecture states that every balanced presentation (a presentation with the
same number of generators and relators) of the trivial group can be transformed into a trivial
presentation by a sequence of Nielsen transformations on the relators together with conjugations
of relators. It was proposed by J. J. Andrews and M. L. Curtis in 1965. It is widely believed
to be false, although no counterexample is known.

A balanced presentation on $n$ generators is modelled as an $n$-tuple $(r_1, \dots, r_n)$ of
elements of the free group on $x_1, \dots, x_n$; the presented group is
`PresentedGroup (Set.range r)`. The trivial presentation is the tuple $(x_1, \dots, x_n)$.

*References:*
- [Wikipedia](https://en.wikipedia.org/wiki/Andrews%E2%80%93Curtis_conjecture)
- [Wikipedia, List of unsolved problems in mathematics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics)
- J. J. Andrews, M. L. Curtis, *Free groups and handlebodies*,
  Proc. Amer. Math. Soc. 16 (1965), 192–195. [doi:10.2307/2033843](https://doi.org/10.2307/2033843)
-/

namespace AndrewsCurtisConjecture

/--
An elementary Andrews–Curtis move on an $n$-tuple $(r_1, \dots, r_n)$ of relators in the free
group on $n$ generators. It replaces a single relator $r_i$ by
- its inverse $r_i^{-1}$,
- the product $r_i r_j$ for some $j \ne i$, or
- a conjugate $w r_i w^{-1}$ for some word $w$,

and leaves the other relators unchanged. These are the Nielsen transformations on the relators
(permutations of the relators are generated by the first two kinds of move) together with
conjugations of relators. The generators are fixed: no stabilization moves are allowed.
-/
inductive Move {n : ℕ} : (Fin n → FreeGroup (Fin n)) → (Fin n → FreeGroup (Fin n)) → Prop
  | inv (r : Fin n → FreeGroup (Fin n)) (i : Fin n) :
      Move r (Function.update r i (r i)⁻¹)
  | mul (r : Fin n → FreeGroup (Fin n)) (i j : Fin n) (hij : i ≠ j) :
      Move r (Function.update r i (r i * r j))
  | conj (r : Fin n → FreeGroup (Fin n)) (i : Fin n) (w : FreeGroup (Fin n)) :
      Move r (Function.update r i (w * r i * w⁻¹))

/--
Two $n$-tuples of relators $r$ and $s$ in the free group on $n$ generators are Andrews–Curtis
equivalent if $r$ can be transformed into $s$ by a finite sequence of elementary
Andrews–Curtis moves.
-/
def ACEquivalent {n : ℕ} (r s : Fin n → FreeGroup (Fin n)) : Prop :=
  Relation.ReflTransGen Move r s

/--
**Andrews–Curtis conjecture.** Every balanced presentation of the trivial group can be
transformed into a trivial presentation by a sequence of Nielsen transformations on the relators
together with conjugations of relators.

Precisely: for every $n$ and every $n$-tuple $(r_1, \dots, r_n)$ of elements of the free group
on $x_1, \dots, x_n$ such that the balanced presentation
$\langle x_1, \dots, x_n \mid r_1, \dots, r_n \rangle$ presents the trivial group, the tuple
$(r_1, \dots, r_n)$ can be transformed into the trivial presentation $(x_1, \dots, x_n)$ by a
finite sequence of elementary Andrews–Curtis moves (replace some $r_i$ by $r_i^{-1}$, by
$r_i r_j$ with $j \ne i$, or by $w r_i w^{-1}$ for a word $w$).
-/
theorem andrews_curtis_conjecture (n : ℕ) (r : Fin n → FreeGroup (Fin n))
    (hr : Subsingleton (PresentedGroup (Set.range r))) :
    ACEquivalent r FreeGroup.of := by
  sorry

end AndrewsCurtisConjecture

theorem AndrewsCurtisConjecture.andrews_curtis_conjecture.disproof : ¬ (type_of% @AndrewsCurtisConjecture.andrews_curtis_conjecture) := sorry
