/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Bass–Quillen conjecture

The Bass–Quillen conjecture relates vector bundles (finitely generated projective modules) over
a regular Noetherian ring $A$ and over the polynomial ring $A[t_1, \dots, t_n]$: it predicts that
extension of scalars $M \mapsto M \otimes_A A[t_1, \dots, t_n]$ is a bijection on isomorphism
classes, i.e. that every vector bundle over $A[t_1, \dots, t_n]$ is extended from $A$.

Mathlib does not yet have regular local rings, so this file defines `IsRegularLocalRing`
(a Noetherian local ring whose Krull dimension equals the dimension of its cotangent space) and
`IsRegularRing` (a ring all of whose localizations at prime ideals are regular local rings).

*References:*
- [Wikipedia, Bass–Quillen conjecture](https://en.wikipedia.org/wiki/Bass%E2%80%93Quillen_conjecture)
- [Wikipedia, List of unsolved problems in mathematics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics)
- [Wikipedia, Regular local ring](https://en.wikipedia.org/wiki/Regular_local_ring)
- H. Bass, *Some problems in "classical" algebraic K-theory*, Algebraic K-Theory II,
  Lecture Notes in Math. 342, Springer (1973).
- D. Quillen, *Projective modules over polynomial rings*, Invent. Math. 36 (1976), 167–171.
- T. Y. Lam, *Serre's problem on projective modules*, Springer Monographs in Mathematics (2006).
-/

open TensorProduct IsLocalRing

namespace BassQuillenConjecture

universe u

/-- A local ring `R` is a *regular local ring* if it is Noetherian and its Krull dimension
$\dim R$ equals the dimension $\dim_k \mathfrak{m}/\mathfrak{m}^2$ of its cotangent space over
the residue field $k = R/\mathfrak{m}$ (equivalently, by Nakayama's lemma, the maximal ideal
$\mathfrak{m}$ can be generated by $\dim R$ elements). -/
class IsRegularLocalRing (R : Type*) [CommRing R] [IsLocalRing R] : Prop where
  isNoetherianRing : IsNoetherianRing R
  ringKrullDim_eq_finrank_cotangentSpace :
    ringKrullDim R = Module.finrank (ResidueField R) (CotangentSpace R)

/-- A commutative ring `A` is *regular* if its localization $A_{\mathfrak p}$ at every prime ideal
$\mathfrak p$ is a regular local ring. (This does not by itself force `A` to be Noetherian; the
Bass–Quillen conjecture is about regular *Noetherian* rings.) -/
class IsRegularRing (A : Type*) [CommRing A] : Prop where
  isRegularLocalRing_localization (p : Ideal A) [p.IsPrime] :
    IsRegularLocalRing (Localization.AtPrime p)

set_option synthInstance.maxHeartbeats 100000 in
/-- The **Bass–Quillen conjecture**: let $A$ be a regular Noetherian (commutative) ring and let
$n \geq 0$. Then $M \mapsto M \otimes_A A[t_1, \dots, t_n]$ induces a bijection between the
isomorphism classes of finitely generated projective modules (vector bundles) over $A$ and those
over the polynomial ring $A[t_1, \dots, t_n]$. Concretely:
* (injectivity) if $M$, $N$ are finitely generated projective $A$-modules with
  $M \otimes_A A[t_1, \dots, t_n] \cong N \otimes_A A[t_1, \dots, t_n]$, then $M \cong N$;
* (surjectivity) every finitely generated projective $A[t_1, \dots, t_n]$-module $P$ is
  *extended from $A$*, i.e. $P \cong M \otimes_A A[t_1, \dots, t_n]$ for some finitely generated
  projective $A$-module $M$.

Here $A[t_1, \dots, t_n]$ is `MvPolynomial (Fin n) A` and $M \otimes_A A[t_1, \dots, t_n]$ is
written `MvPolynomial (Fin n) A ⊗[A] M`, with its natural $A[t_1, \dots, t_n]$-module structure.

Injectivity is automatic (specialise $t_1 = \dots = t_n = 0$); the content of the conjecture is
the surjectivity statement. Wikipedia states the conjecture rank by rank, as a bijection
$\operatorname{Vect}_r(A) \to \operatorname{Vect}_r(A[t_1, \dots, t_n])$ for every $r$; since
extension of scalars preserves the rank and every idempotent of $A[t_1, \dots, t_n]$ lies in
$A$, this is equivalent to the statement for all finitely generated projective modules. -/
theorem bass_quillen_conjecture (A : Type u) [CommRing A] [IsNoetherianRing A] [IsRegularRing A]
    (n : ℕ) :
    (∀ (M N : Type u) [AddCommGroup M] [Module A M] [Module.Finite A M] [Module.Projective A M]
        [AddCommGroup N] [Module A N] [Module.Finite A N] [Module.Projective A N],
      Nonempty (MvPolynomial (Fin n) A ⊗[A] M ≃ₗ[MvPolynomial (Fin n) A]
        MvPolynomial (Fin n) A ⊗[A] N) → Nonempty (M ≃ₗ[A] N)) ∧
    (∀ (P : Type u) [AddCommGroup P] [Module (MvPolynomial (Fin n) A) P]
        [Module.Finite (MvPolynomial (Fin n) A) P] [Module.Projective (MvPolynomial (Fin n) A) P],
      ∃ (M : Type u) (_ : AddCommGroup M) (_ : Module A M),
        Module.Finite A M ∧ Module.Projective A M ∧
          Nonempty (MvPolynomial (Fin n) A ⊗[A] M ≃ₗ[MvPolynomial (Fin n) A] P)) := by
  sorry

end BassQuillenConjecture

theorem BassQuillenConjecture.bass_quillen_conjecture.disproof : ¬ (type_of% @BassQuillenConjecture.bass_quillen_conjecture) := sorry
