/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Birch–Tate conjecture

Let $F$ be a totally real number field with ring of integers $\mathcal{O}_F$. The group
$K_2(\mathcal{O}_F)$, also called the *tame kernel* of $F$, is the center of the Steinberg group
$\mathrm{St}(\mathcal{O}_F)$. Let $N = w_2(F)$ be the largest positive integer such that the
Galois group of $F(\zeta_N)/F$ is an elementary abelian $2$-group. The Birch–Tate conjecture
states that
$$\#K_2(\mathcal{O}_F) = |N \cdot \zeta_F(-1)|,$$
where $\zeta_F$ is the Dedekind zeta function of $F$, meromorphically continued to $\mathbb{C}$.

Mathlib has neither the Steinberg group nor $K_2$, so they are defined here by Milnor's
presentation. Mathlib's `NumberField.dedekindZeta` is only the Dirichlet series, which does not
converge at $s = -1$, so the value $\zeta_F(-1)$ is taken from any function holomorphic on
$\mathbb{C} \setminus \{1\}$ that agrees with the Dirichlet series on the half-plane
$\operatorname{Re}(s) > 1$. Such a function exists (Hecke) and is unique by the identity theorem.

*References:*
- [Wikipedia: Birch–Tate conjecture](https://en.wikipedia.org/wiki/Birch%E2%80%93Tate_conjecture)
- [Wikipedia: List of unsolved problems in mathematics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics)
- J. Tate, *Symbols in arithmetic*, Actes du Congrès International des Mathématiciens
  (Nice, 1970), Tome 1, Gauthier-Villars, 1971, pp. 201–211.
- J. Milnor, *Introduction to algebraic K-theory*, Annals of Mathematics Studies 72,
  Princeton University Press, 1971, §5 and §10.
-/

open NumberField

namespace BirchTateConjecture

section SteinbergGroup

variable (R : Type*) [Ring R]

/-- The index of a generator $x_{ij}(r)$ of the Steinberg group of a ring `R`: a pair of distinct
indices `i ≠ j` and a ring element `r`. -/
structure SteinbergGenerator where
  /-- The row index. -/
  i : ℕ
  /-- The column index. -/
  j : ℕ
  /-- The row and column indices are distinct. -/
  ne : i ≠ j
  /-- The ring element. -/
  r : R

/-- The Steinberg relations on the generators $x_{ij}(r)$, as elements of the free group
(Milnor, §5):
* $x_{ij}(r) x_{ij}(s) = x_{ij}(r + s)$,
* $[x_{ij}(r), x_{jk}(s)] = x_{ik}(rs)$ for $i \neq k$,
* $[x_{ij}(r), x_{kl}(s)] = 1$ for $j \neq k$ and $i \neq l$,

where $[a, b] = a b a^{-1} b^{-1}$ is Mathlib's commutator `⁅a, b⁆`. -/
inductive SteinbergRel : FreeGroup (SteinbergGenerator R) → Prop
  | add {i j : ℕ} (h : i ≠ j) (r s : R) :
    SteinbergRel (FreeGroup.of ⟨i, j, h, r⟩ * FreeGroup.of ⟨i, j, h, s⟩ *
      (FreeGroup.of ⟨i, j, h, r + s⟩)⁻¹)
  | commutator_eq {i j k : ℕ} (hij : i ≠ j) (hjk : j ≠ k) (hik : i ≠ k) (r s : R) :
    SteinbergRel (⁅FreeGroup.of (SteinbergGenerator.mk i j hij r),
      FreeGroup.of (SteinbergGenerator.mk j k hjk s)⁆ *
        (FreeGroup.of ⟨i, k, hik, r * s⟩)⁻¹)
  | commutator_one {i j k l : ℕ} (hij : i ≠ j) (hkl : k ≠ l) (hjk : j ≠ k) (hil : i ≠ l)
    (r s : R) :
    SteinbergRel ⁅FreeGroup.of (SteinbergGenerator.mk i j hij r),
      FreeGroup.of (SteinbergGenerator.mk k l hkl s)⁆

/-- The (stable) Steinberg group $\mathrm{St}(R)$ of a ring `R`: the group generated by the
symbols $x_{ij}(r)$, for distinct indices `i ≠ j` in `ℕ` and `r : R`, subject to the Steinberg
relations `SteinbergRel`. -/
abbrev SteinbergGroup : Type _ :=
  PresentedGroup {w | SteinbergRel R w}

/-- The group $K_2(R)$ of a ring `R`, defined as the center of the Steinberg group
$\mathrm{St}(R)$. For the ring of integers $\mathcal{O}_F$ of a number field $F$, this group is
also known as the tame kernel of $F$. -/
def K₂ : Subgroup (SteinbergGroup R) :=
  Subgroup.center (SteinbergGroup R)

variable {R}

/-- The generator $x_{ij}(r)$ of the Steinberg group $\mathrm{St}(R)$. -/
def SteinbergGroup.x {i j : ℕ} (h : i ≠ j) (r : R) : SteinbergGroup R :=
  PresentedGroup.of ⟨i, j, h, r⟩

end SteinbergGroup

/-- `w₂ F` is the largest positive integer `N` such that the Galois group of the cyclotomic
extension $F(\zeta_N)/F$ is an elementary abelian $2$-group, i.e. every element of
$\mathrm{Gal}(F(\zeta_N)/F)$ squares to the identity (a group of exponent dividing $2$ is
automatically abelian). Here $F(\zeta_N)$ is `CyclotomicField N F`, the splitting field of the
`N`-th cyclotomic polynomial over `F`.

For a number field `F` the set of such `N` is bounded (its maximum is Tate's invariant
$w_2(F)$), so the supremum is a maximum. -/
noncomputable def w₂ (F : Type*) [Field F] : ℕ :=
  sSup {N : ℕ | 0 < N ∧ ∀ σ : CyclotomicField N F ≃ₐ[F] CyclotomicField N F, σ ^ 2 = 1}

/-- **Birch–Tate conjecture.** Let $F$ be a totally real number field, let
$K_2(\mathcal{O}_F)$ be the center of the Steinberg group of its ring of integers, and let
$N = w_2(F)$ be the largest positive integer such that the Galois group of $F(\zeta_N)/F$ is an
elementary abelian $2$-group. Then
$$\#K_2(\mathcal{O}_F) = |N \cdot \zeta_F(-1)|,$$
where $\zeta_F$ is the meromorphic continuation of the Dedekind zeta function of $F$.

The continuation is represented by any function `ζ : ℂ → ℂ` that is holomorphic on
$\mathbb{C} \setminus \{1\}$ and agrees with the Dirichlet series `dedekindZeta F` on the
half-plane $\operatorname{Re}(s) > 1$; such a function exists (Hecke) and its value at $-1$ is
uniquely determined by the identity theorem. Since $\zeta_F(-1) \neq 0$ for totally real $F$,
the equality also forces $K_2(\mathcal{O}_F)$ to be finite (a theorem of Garland). -/
theorem birch_tate_conjecture (F : Type*) [Field F] [NumberField F] [IsTotallyReal F]
    (ζ : ℂ → ℂ) (hζ : DifferentiableOn ℂ ζ {1}ᶜ)
    (hζ' : ∀ s : ℂ, 1 < s.re → ζ s = dedekindZeta F s) :
    (Nat.card (K₂ (𝓞 F)) : ℝ) = ‖(w₂ F : ℂ) * ζ (-1)‖ := by
  sorry

end BirchTateConjecture

theorem BirchTateConjecture.birch_tate_conjecture.disproof : ¬ (type_of% @BirchTateConjecture.birch_tate_conjecture) := sorry
