/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# The elliptic curve discrete logarithm problem in sub-exponential time

Let $E$ be an elliptic curve over a finite field $\mathbb{F}_q$, let $P \in E(\mathbb{F}_q)$
and let $Q$ be in the cyclic subgroup generated by $P$. The *discrete logarithm problem* on $E$
asks for an integer $k$ with $Q = kP$. The best known classical algorithms for a general elliptic
curve (baby-step giant-step, Pollard's rho) run in time about $\sqrt{q} = 2^{\Theta(\log q)}$,
which is exponential in the input size $\Theta(\log q)$.

Wikipedia asks: *Can a discrete logarithm on an elliptic curve be computed in sub-exponential
time?*

We formalise this as the existence of a deterministic Turing machine (the `TM2` model of
`Mathlib.Computability.TMComputable`, as in `FormalConjectures/Millenium/PvsNP.lean`) that
solves the discrete logarithm problem on every elliptic curve over every finite field within
$2^{o(n)}$ steps, where $n$ is the length of the input. Finite fields are presented as
$\mathbb{F}_p[X]/(f)$ with $f$ monic irreducible, curves by a Weierstrass equation, and the input
is a fixed binary encoding of all this data, so that $n = \Theta(\log q)$.

Randomised algorithms with expected running time bounds, which the cryptographic literature
often allows, are not modelled; only the worst-case running time of deterministic classical
machines is considered. Quantum algorithms are not covered.

*References:*
- [Wikipedia, Discrete logarithm](https://en.wikipedia.org/wiki/discrete_logarithm)
- [Wikipedia, List of unsolved problems in mathematics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics)
- [Wikipedia, Elliptic-curve cryptography](https://en.wikipedia.org/wiki/Elliptic-curve_cryptography)
-/

open Computability Turing Polynomial Filter

namespace DiscreteLogarithm2

/--
An input to the elliptic curve discrete logarithm problem. It consists of
- a prime `p`,
- a monic irreducible polynomial `f` over `𝔽_p = ZMod p`, presenting the finite field
  `𝔽_q = 𝔽_p[X]/(f) = AdjoinRoot f` with `q = p ^ deg f`,
- an elliptic curve `E` over `𝔽_q`, given by a (long) Weierstrass equation,
- two points `P` and `Q` of `E(𝔽_q)`.

Every finite field, and every elliptic curve over it, arises this way up to isomorphism.
-/
structure Input where
  /-- The characteristic of the finite field. -/
  p : ℕ
  [hp : Fact p.Prime]
  /-- The monic irreducible polynomial `f` presenting the finite field `𝔽_p[X]/(f)`. -/
  f : (ZMod p)[X]
  monic : f.Monic
  [irreducible : Fact (Irreducible f)]
  /-- The elliptic curve, given by a Weierstrass equation over `𝔽_p[X]/(f)`. -/
  E : WeierstrassCurve (AdjoinRoot f)
  [elliptic : E.IsElliptic]
  /-- The base point. -/
  P : E.toAffine.Point
  /-- The point whose discrete logarithm with respect to `P` is sought. -/
  Q : E.toAffine.Point

attribute [instance] Input.hp Input.irreducible Input.elliptic

namespace Input

variable (I : Input)

/--
The list of the `deg f` coefficients, as natural numbers `< p`, of the unique representative of
degree `< deg f` of an element of `𝔽_p[X]/(f)`.
-/
noncomputable def encodeElem (x : AdjoinRoot I.f) : List ℕ :=
  (List.range I.f.natDegree).map fun i => ((AdjoinRoot.modByMonicHom I.monic x).coeff i).val

/--
A point of `E(𝔽_q)` is encoded by the tag `0` if it is the point at infinity, and by the tag `1`
followed by the encodings of its two affine coordinates otherwise.
-/
noncomputable def encodePoint : I.E.toAffine.Point → List ℕ
  | .zero => [0]
  | .some (x := x) (y := y) _ => 1 :: (I.encodeElem x ++ I.encodeElem y)

/--
The list of natural numbers describing an input: the prime `p`, the degree `n` of `f`, the `n`
lower coefficients of `f` (the leading coefficient is `1`), the coefficients `a₁, a₂, a₃, a₄, a₆`
of the Weierstrass equation of `E`, and the two points `P` and `Q`.
-/
noncomputable def toNatList : List ℕ :=
  [I.p, I.f.natDegree] ++ (List.range I.f.natDegree).map (fun i => (I.f.coeff i).val) ++
    I.encodeElem I.E.a₁ ++ I.encodeElem I.E.a₂ ++ I.encodeElem I.E.a₃ ++ I.encodeElem I.E.a₄ ++
    I.encodeElem I.E.a₆ ++ I.encodePoint I.P ++ I.encodePoint I.Q

end Input

/--
A list of natural numbers is written over the standard Turing machine alphabet `Γ'` by writing
each number in binary (via `Computability.encodeNat`, least significant bit first) followed by a
`comma`.
-/
def encodeNatList (l : List ℕ) : List Γ' :=
  (l.map fun k => (encodeNat k).map Γ'.bit ++ [Γ'.comma]).flatten

/-- The binary encoding of an input, over the alphabet `Γ'`. Its length is `Θ(log q)`. -/
noncomputable def Input.encode (I : Input) : List Γ' :=
  encodeNatList I.toNatList

/--
A time bound `T : ℕ → ℕ` is *sub-exponential* if `T n = 2 ^ o(n)`, that is, if for every
`ε > 0` we have `T n ≤ 2 ^ (ε * n)` for all sufficiently large `n`.
-/
def IsSubexponential (T : ℕ → ℕ) : Prop :=
  ∀ ε : ℝ, 0 < ε → ∀ᶠ n : ℕ in atTop, (T n : ℝ) ≤ 2 ^ (ε * n)

/--
**Elliptic curve discrete logarithms in sub-exponential time.**

Can a discrete logarithm on an elliptic curve be computed in sub-exponential time?

That is, is there a deterministic Turing machine `M` and a sub-exponential time bound
`T n = 2 ^ o(n)` such that for every prime `p`, every finite field `𝔽_q = 𝔽_p[X]/(f)` with `f`
monic irreducible, every elliptic curve `E` over `𝔽_q` given by a Weierstrass equation and all
points `P`, `Q` of `E(𝔽_q)` with `Q` in the subgroup generated by `P`, the machine `M`, started
on the binary encoding of `(p, f, E, P, Q)`, halts within `T (input length)` steps and outputs
the binary encoding of a natural number `k` with `Q = k • P`?

The input length is `Θ(log q)`, so the generic algorithms, which take about `√q` steps, are
exponential. Only the worst-case running time of deterministic (classical) machines is
considered; randomised algorithms are not modelled, and Shor's algorithm solves the problem in
polynomial time on a quantum computer.
-/
theorem discrete_logarithm_2 :
    ∃ (M : TM2ComputableAux Γ' Γ') (T : ℕ → ℕ), IsSubexponential T ∧
      ∀ I : Input, (∃ k : ℕ, I.Q = k • I.P) → ∃ k : ℕ, I.Q = k • I.P ∧
        Nonempty (TM2OutputsInTime M.tm (I.encode.map M.inputAlphabet.symm)
          (some (((encodeNat k).map Γ'.bit).map M.outputAlphabet.symm)) (T I.encode.length)) := by
  sorry

end DiscreteLogarithm2

theorem DiscreteLogarithm2.discrete_logarithm_2.disproof : ¬ (type_of% @DiscreteLogarithm2.discrete_logarithm_2) := sorry
