/-
Copyright 2025 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# (Exponential) periods

Kontsevich and Zagier define a *period* as a complex number whose real and imaginary parts are
values of absolutely convergent integrals of rational functions with rational coefficients over
domains in $\mathbb{R}^n$ given by polynomial inequalities with rational coefficients. The
periods form a countable ring $\mathcal{P}$ with
$\overline{\mathbb{Q}} \subset \mathcal{P} \subset \mathbb{C}$. Allowing the integrand to also
contain the exponential of an algebraic function gives the ring of *exponential periods*
$\mathcal{EP}$.

Wikipedia lists the open problem "Which transcendental numbers are (exponential) periods?". The
concrete conjectures recorded there, going back to Kontsevich and Zagier, are that $1/\pi$,
Euler's number $e$ and the Euler–Mascheroni constant $\gamma$ are not periods. Both $e$ and
$\gamma$ are known to be exponential periods.

*References:*
- [Wikipedia, Period (algebraic geometry)](https://en.wikipedia.org/wiki/Period_%28algebraic_geometry%29)
- [Wikipedia, List of unsolved problems in mathematics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics)
- [KZ01] Kontsevich, M., Zagier, D., *Periods*. In: Mathematics Unlimited — 2001 and Beyond,
  Springer, 2001, pp. 771–808.
- [La13] Lagarias, J. C., *Euler's constant: Euler's work and modern developments*.
  Bull. Amer. Math. Soc. 50 (2013), 527–628. [arXiv:1303.1856](https://arxiv.org/abs/1303.1856)
- [MS14] Müller-Stach, S., *What is a period?*. Notices Amer. Math. Soc. 61 (2014).
  [arXiv:1407.2388](https://arxiv.org/abs/1407.2388)
-/

namespace ExponentialPeriods

open MeasureTheory MvPolynomial Real

/--
A subset of $\mathbb{R}^n$ is *semialgebraic over $\mathbb{Q}$* if it belongs to the Boolean
algebra of sets generated by the sets $\{x \in \mathbb{R}^n \mid p(x) \geq 0\}$ with
$p \in \mathbb{Q}[x_1, \ldots, x_n]$. These are the domains "given by polynomial inequalities
with rational coefficients" in the definition of a period.
-/
def IsRatSemialgebraic {n : ℕ} (D : Set (Fin n → ℝ)) : Prop :=
  D ∈ BooleanSubalgebra.closure {s | ∃ p : MvPolynomial (Fin n) ℚ, s = {x | 0 ≤ aeval x p}}

/--
A real number $a$ is a *period* (Kontsevich–Zagier) if it is the value of an absolutely
convergent integral
$$a = \int_D \frac{f(x_1, \ldots, x_n)}{g(x_1, \ldots, x_n)} \, dx_1 \cdots dx_n$$
of a rational function $f / g$ with $f, g \in \mathbb{Q}[x_1, \ldots, x_n]$ over a domain
$D \subseteq \mathbb{R}^n$ that is semialgebraic over $\mathbb{Q}$.

Absolute convergence is encoded by `IntegrableOn` with respect to Lebesgue measure on
`Fin n → ℝ`. Lean's convention `x / 0 = 0` is harmless: for `g ≠ 0` the zero set of `g` is
Lebesgue-null, and for `g = 0` the integral is `0`, which is a period.
-/
def IsRealPeriod (a : ℝ) : Prop :=
  ∃ (n : ℕ) (D : Set (Fin n → ℝ)) (f g : MvPolynomial (Fin n) ℚ),
    IsRatSemialgebraic D ∧ IntegrableOn (fun x => aeval x f / aeval x g) D ∧
      a = ∫ x in D, aeval x f / aeval x g

/--
A complex number is a *period* if its real and imaginary parts are (real) periods.
-/
def IsPeriod (z : ℂ) : Prop :=
  IsRealPeriod z.re ∧ IsRealPeriod z.im

/--
**Conjecture (Kontsevich–Zagier; Lagarias [La13, Conjecture 1.2]).** The Euler–Mascheroni
constant $\gamma$ is not a period.

Since every algebraic number is a period, this would imply that $\gamma$ is transcendental.
Note that $\gamma$ is known to be an exponential period.
-/
theorem exponential_periods.parts.iii : ¬ IsPeriod eulerMascheroniConstant := by
  sorry

end ExponentialPeriods

theorem ExponentialPeriods.exponential_periods.parts.iii.disproof : ¬ (type_of% @ExponentialPeriods.exponential_periods.parts.iii) := sorry
