/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Fröberg conjecture

The Fröberg conjecture predicts the Hilbert series of the quotient of
$\mathbb{C}[x_1, \ldots, x_n]$ by the ideal generated by generic forms of prescribed degrees.

*References:*
* [Wikipedia](https://en.wikipedia.org/wiki/Fr%C3%B6berg_conjecture)
* [Wikipedia, List of unsolved problems in mathematics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics)
* R. Fröberg, *An inequality for Hilbert series of graded algebras*,
  Math. Scand. 56 (1985), 117–144.
  [doi:10.7146/math.scand.a-12092](https://doi.org/10.7146/math.scand.a-12092)
-/

namespace FrobergConjecture

section HilbertSeries

open MvPolynomial

variable {σ K : Type*} [Field K]

/-- The Hilbert function of the graded algebra $K[x_i : i \in σ] / I$: its value at `d` is the
dimension of the image in the quotient of the space of homogeneous polynomials of degree `d`
(this image is finite-dimensional when `σ` is finite). When `I` is a homogeneous ideal, this is
the dimension of the degree `d` component of the quotient. -/
noncomputable def hilbertFunction (I : Ideal (MvPolynomial σ K)) (d : ℕ) : ℕ :=
  Module.finrank K ((homogeneousSubmodule σ K d).map (Ideal.Quotient.mkₐ K I).toLinearMap)

/-- The Hilbert series $\sum_{d \ge 0} \dim_K (K[x_i : i \in σ] / I)_d \, t^d$ of the graded
algebra $K[x_i : i \in σ] / I$, as a formal power series with integer coefficients. -/
noncomputable def hilbertSeries (I : Ideal (MvPolynomial σ K)) : PowerSeries ℤ :=
  PowerSeries.mk fun d => (hilbertFunction I d : ℤ)

end HilbertSeries

section Series

open PowerSeries

/-- The formal power series
$$\frac{(1 - t^{a_1})(1 - t^{a_2}) \cdots (1 - t^{a_k})}{(1 - t)^n}
  = (1 + t + t^2 + \cdots)^n (1 - t^{a_1})(1 - t^{a_2}) \cdots (1 - t^{a_k})$$
with integer coefficients, where `n` is the number of variables and `a 0, …, a (k - 1)` are the
degrees of the forms. -/
noncomputable def frobergSeries (n : ℕ) {k : ℕ} (a : Fin k → ℕ) : PowerSeries ℤ :=
  (∏ i, (1 - X ^ a i)) * (invOneSubPow ℤ n : ℤ⟦X⟧)

open scoped Classical in
/-- The power series `f` truncated at its first negative coefficient: the coefficient of `t ^ d`
is left unchanged if all the coefficients of `t ^ e` with `e ≤ d` are nonnegative, and it is
replaced by `0` otherwise. -/
noncomputable def truncateAtFirstNegative (f : PowerSeries ℤ) : PowerSeries ℤ :=
  PowerSeries.mk fun d => if ∃ e ≤ d, coeff e f < 0 then 0 else coeff d f

end Series

section Generic

open MvPolynomial

/-- A property `p` of `k`-tuples `g` of homogeneous polynomials in `n` variables over `ℂ`, of
degrees `a 0, …, a (k - 1)`, holds for *generic* such tuples if it holds on a nonempty
Zariski-open subset of the affine space of all such tuples. Since `ℂ` is infinite, this means
that there is a nonzero polynomial `P` in the coefficients of the forms (one indeterminate for
each `i : Fin k` and each monomial of degree `a i`) such that `p g` holds for every tuple `g` of
forms of the given degrees at whose coefficients `P` does not vanish. -/
def HoldsForGenericForms (n : ℕ) {k : ℕ} (a : Fin k → ℕ)
    (p : (Fin k → MvPolynomial (Fin n) ℂ) → Prop) : Prop :=
  ∃ P : MvPolynomial (Σ i : Fin k, {m : Fin n →₀ ℕ // m.degree = a i}) ℂ, P ≠ 0 ∧
    ∀ g : Fin k → MvPolynomial (Fin n) ℂ, (∀ i, (g i).IsHomogeneous (a i)) →
      eval (fun x => coeff x.2.1 (g x.1)) P ≠ 0 → p g

end Generic

/-- **Fröberg conjecture** (Fröberg 1985, p. 120).
Let $g_1, g_2, \ldots, g_k \in \mathbb{C}[x_1, x_2, \ldots, x_n]$ be generic homogeneous
polynomials of degrees $a_1, a_2, \ldots, a_k$ respectively. Then the Hilbert series of
$\mathbb{C}[x_1, x_2, \ldots, x_n] / \langle g_1, g_2, \ldots, g_k \rangle$ is
$$(1 + t + t^2 + \cdots)^n (1 - t^{a_1})(1 - t^{a_2}) \cdots (1 - t^{a_k})
  = \frac{(1 - t^{a_1})(1 - t^{a_2}) \cdots (1 - t^{a_k})}{(1 - t)^n},$$
truncated at its first negative term.

Here "generic" means that, for every `n`, `k` and degrees `a`, the conclusion holds for all
tuples of forms in a nonempty Zariski-open subset of the affine space of `k`-tuples of forms of
degrees `a 0, …, a (k - 1)`; see `FrobergConjecture.HoldsForGenericForms`. -/
theorem froberg_conjecture (n k : ℕ) (a : Fin k → ℕ) :
    HoldsForGenericForms n a fun g =>
      hilbertSeries (Ideal.span (Set.range g)) = truncateAtFirstNegative (frobergSeries n a) := by
  sorry

end FrobergConjecture

theorem FrobergConjecture.froberg_conjecture.disproof : ¬ (type_of% @FrobergConjecture.froberg_conjecture) := sorry
