/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Nagata's conjecture on curves

Nagata's conjecture on curves governs the minimal degree required for a plane algebraic curve to
pass through a collection of very general points with prescribed multiplicities.

**Nagata's conjecture.** Suppose $p_1, \dots, p_r$ are very general points in $\mathbb{P}^2$ and
$m_1, \dots, m_r$ are given positive integers. Then for $r > 9$ any curve $C$ in $\mathbb{P}^2$
that passes through each of the points $p_i$ with multiplicity $m_i$ must satisfy
$$\deg C > \frac{1}{\sqrt r} \sum_{i=1}^r m_i.$$

The condition $r > 9$ is necessary: for $r = 9$ a cubic through nine points has
$\deg C = 3 = \frac{1}{\sqrt 9} \sum_{i=1}^9 1$. The only known case is when $r$ is a perfect
square, which was proved by Nagata [Nag59].

## Formalisation choices

* We work over $\mathbb{C}$, and $\mathbb{P}^2$ is the projectivization `ℙ ℂ (Fin 3 → ℂ)` of
  $\mathbb{C}^3$.
* A plane curve of degree $d$ is a nonzero homogeneous polynomial $F$ of degree $d$ in the
  homogeneous coordinates $X_0, X_1, X_2$; it need not be reduced or irreducible.
* The curve $F = 0$ passes through $p$ with multiplicity (at least) $m$ iff $F$ lies in the $m$-th
  power of the homogeneous ideal `pointIdeal p` of $p$, which is generated by the linear forms
  vanishing at $p$. In affine coordinates centred at $p$ this says that $F$ has no terms of
  degree $< m$, the usual definition of the multiplicity of a curve at a point.
* "Very general" has its standard meaning: the property holds for all $r$-tuples of points
  outside a countable union of proper Zariski closed subsets of $(\mathbb{P}^2)^r$. Since
  $\mathbb{C}$ is uncountable, such tuples exist.

*References:*
* [Wikipedia: Nagata's conjecture on curves](https://en.wikipedia.org/wiki/Nagata%27s_conjecture_on_curves)
* [Wikipedia: List of unsolved problems in mathematics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics)
* [Nag59] M. Nagata, *On the 14-th problem of Hilbert*, Amer. J. Math. 81 (1959), 766–772.
* [Har01] B. Harbourne, *On Nagata's conjecture*, J. Algebra 236 (2001), 692–702,
  [arXiv:math/9909093](https://arxiv.org/abs/math/9909093)
-/

namespace NagatasConjectureOnCurves

open MvPolynomial
open scoped LinearAlgebra.Projectivization

variable {K : Type*} [Field K]

/-- The homogeneous ideal of a point `p ∈ ℙ²` in the homogeneous coordinate ring
`K[X₀, X₁, X₂]`: the ideal generated by the linear forms vanishing at `p`. -/
def pointIdeal (p : ℙ K (Fin 3 → K)) : Ideal (MvPolynomial (Fin 3) K) :=
  Ideal.span {L | L.IsHomogeneous 1 ∧ eval p.rep L = 0}

/-- A polynomial `F ∈ K[X₀, X₁, X₂]` has *multiplicity at least `m`* at a point `p ∈ ℙ²`
if `F` lies in the `m`-th power of the homogeneous ideal of `p`. For a nonzero homogeneous
`F`, this says that the plane curve `F = 0` passes through `p` with multiplicity at least `m`. -/
def HasMultiplicityAtLeast (F : MvPolynomial (Fin 3) K) (p : ℙ K (Fin 3 → K)) (m : ℕ) :
    Prop :=
  F ∈ pointIdeal p ^ m

/-- A subset of `(ℙ²)^r` is Zariski closed if it is the common zero locus of a family of
polynomials in the `3r` homogeneous coordinates `X i j` (`i : Fin r`, `j : Fin 3`), each of which
is homogeneous separately in each of the `r` blocks of variables `X i 0, X i 1, X i 2`.
Such a zero locus does not depend on the choice of homogeneous coordinates of the points. -/
def IsZariskiClosed {r : ℕ} (Z : Set (Fin r → ℙ K (Fin 3 → K))) : Prop :=
  ∃ S : Set (MvPolynomial (Fin r × Fin 3) K),
    (∀ F ∈ S, ∃ d : Fin r → ℕ, F.IsWeightedHomogeneous (fun ij => Pi.single ij.1 1) d) ∧
    Z = {p | ∀ F ∈ S, eval (fun ij => (p ij.1).rep ij.2) F = 0}

/-- A property `P` of `r`-tuples of points of `ℙ²` holds for *very general* points if it holds
for all tuples outside a countable union of proper Zariski closed subsets of `(ℙ²)^r`.
(Finite unions are covered by padding the family with the proper closed set `∅`.) -/
def ForVeryGeneral {r : ℕ} (P : (Fin r → ℙ K (Fin 3 → K)) → Prop) : Prop :=
  ∃ Z : ℕ → Set (Fin r → ℙ K (Fin 3 → K)),
    (∀ n, IsZariskiClosed (Z n) ∧ Z n ≠ Set.univ) ∧ ∀ p ∉ ⋃ n, Z n, P p

/-- **Nagata's conjecture on curves.** Suppose $p_1, \dots, p_r$ are very general points in
$\mathbb{P}^2$ and $m_1, \dots, m_r$ are given positive integers. Then for $r > 9$ any curve $C$ in
$\mathbb{P}^2$ that passes through each of the points $p_i$ with multiplicity $m_i$ must satisfy
$$\deg C > \frac{1}{\sqrt r} \sum_{i=1}^r m_i.$$

Here a curve of degree $d$ is a nonzero homogeneous polynomial $F$ of degree $d$ (not necessarily
reduced or irreducible), and "with multiplicity $m_i$" means with multiplicity at least $m_i$,
i.e. $F \in I(p_i)^{m_i}$ where $I(p_i)$ is the homogeneous ideal of $p_i$. -/
theorem nagatas_conjecture_on_curves (r : ℕ) (hr : 9 < r) (m : Fin r → ℕ)
    (hm : ∀ i, 0 < m i) :
    ForVeryGeneral fun p : Fin r → ℙ ℂ (Fin 3 → ℂ) =>
      ∀ (d : ℕ) (F : MvPolynomial (Fin 3) ℂ), F ≠ 0 → F.IsHomogeneous d →
        (∀ i, HasMultiplicityAtLeast F (p i) (m i)) → (∑ i, (m i : ℝ)) / √r < d := by
  sorry

section Tests

end Tests

end NagatasConjectureOnCurves

theorem NagatasConjectureOnCurves.nagatas_conjecture_on_curves.disproof : ¬ (type_of% @NagatasConjectureOnCurves.nagatas_conjecture_on_curves) := sorry
