/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjecturesUtil

/-!
# Serre's positivity conjecture

Let $R$ be a (Noetherian) commutative regular local ring and let $P, Q$ be prime ideals of $R$
such that $R/P \otimes_R R/Q$ has finite length. Serre defined the intersection multiplicity of
$R/P$ and $R/Q$ by
$$\chi(R/P, R/Q) := \sum_{i \ge 0} (-1)^i \ell_R(\operatorname{Tor}_i^R(R/P, R/Q)),$$
where $\ell_R$ denotes the length of an $R$-module. The sum is finite because a regular local ring
has finite global dimension.

Serre's *positivity conjecture* states that if $\dim(R/P) + \dim(R/Q) = \dim(R)$ then
$\chi(R/P, R/Q) > 0$. It is the last of Serre's four multiplicity conjectures that remains open
in general.

*References:*
- [Wikipedia, Serre's multiplicity
  conjectures](https://en.wikipedia.org/wiki/Serre%27s_multiplicity_conjectures)
- [Wikipedia, List of unsolved problems in
  mathematics](https://en.wikipedia.org/wiki/List_of_unsolved_problems_in_mathematics#Algebra)
- J.-P. Serre, *Local Algebra*, Springer Monographs in Mathematics, 2000.
-/

namespace SerresPositivityConjecture

universe u

open CategoryTheory IsLocalRing

open scoped TensorProduct

/-- A commutative ring $R$ is a *regular local ring* if it is a Noetherian local ring whose Krull
dimension equals the dimension of its cotangent space $\mathfrak{m} / \mathfrak{m}^2$ over the
residue field $R / \mathfrak{m}$ (equivalently, by Nakayama's lemma, the maximal ideal
$\mathfrak{m}$ can be generated by $\dim R$ elements). -/
class IsRegularLocalRing (R : Type*) [CommRing R] : Prop
    extends IsLocalRing R, IsNoetherianRing R where
  finrank_cotangentSpace_eq_ringKrullDim :
    Module.finrank (ResidueField R) (CotangentSpace R) = ringKrullDim R

/-- A field is a regular local ring (of dimension $0$). -/
instance (K : Type*) [Field K] : IsRegularLocalRing K where
  finrank_cotangentSpace_eq_ringKrullDim := by
    rw [finrank_cotangentSpace_eq_zero, ringKrullDim_eq_zero_of_field, Nat.cast_zero]

/-- A discrete valuation ring is a regular local ring (of dimension $1$). -/
instance (R : Type*) [CommRing R] [IsDomain R] [IsDiscreteValuationRing R] :
    IsRegularLocalRing R where
  finrank_cotangentSpace_eq_ringKrullDim := by
    rw [finrank_CotangentSpace_eq_one,
      IsPrincipalIdealRing.ringKrullDim_eq_one R (IsDiscreteValuationRing.not_isField R),
      Nat.cast_one]

variable (R : Type u) [CommRing R]

/-- **Serre's intersection multiplicity** of two modules $M$ and $N$ over a commutative ring $R$:
$$\chi(M, N) := \sum_{i \ge 0} (-1)^i \ell_R(\operatorname{Tor}_i^R(M, N)),$$
where $\ell_R$ denotes the length of an $R$-module.

This is meaningful when every $\operatorname{Tor}_i^R(M, N)$ has finite length and only finitely
many of them are nonzero, e.g. when $R$ is a regular local ring (which has finite global
dimension), $M$ and $N$ are finitely generated and $M \otimes_R N$ has finite length. Outside of
this situation the value is a junk value: an infinite length is counted as $0$ (via `ENat.toNat`),
and a sum with infinitely many nonzero terms is $0$ (via `finsum`). -/
noncomputable def intersectionMultiplicity (M N : Type u) [AddCommGroup M] [Module R M]
    [AddCommGroup N] [Module R N] : ℤ :=
  ∑ᶠ i : ℕ, (-1 : ℤ) ^ i *
    (Module.length R
      (((Tor (ModuleCat.{u} R) i).obj (ModuleCat.of R M)).obj (ModuleCat.of R N))).toNat

/-- **Serre's positivity conjecture**

Let $R$ be a commutative regular local ring and let $P, Q$ be prime ideals of $R$ such that
$\ell_R(R/P \otimes_R R/Q) < \infty$ (Serre's standing hypothesis, needed for
$\chi(R/P, R/Q) = \sum_{i \ge 0} (-1)^i \ell_R(\operatorname{Tor}_i^R(R/P, R/Q))$ to be defined).
If $\dim(R/P) + \dim(R/Q) = \dim(R)$, then $\chi(R/P, R/Q) > 0$. -/
theorem serres_positivity_conjecture [IsRegularLocalRing R] (P Q : Ideal R) [P.IsPrime] [Q.IsPrime]
    (hfin : Module.length R ((R ⧸ P) ⊗[R] (R ⧸ Q)) < ⊤)
    (hdim : ringKrullDim (R ⧸ P) + ringKrullDim (R ⧸ Q) = ringKrullDim R) :
    0 < intersectionMultiplicity R (R ⧸ P) (R ⧸ Q) := by
  sorry

end SerresPositivityConjecture

theorem SerresPositivityConjecture.serres_positivity_conjecture.disproof : ¬ (type_of% @SerresPositivityConjecture.serres_positivity_conjecture) := sorry
